### ISSUE TITLE
[infrastructure as a code]: Azure

### ISSUE THREAD

**Issue by iamtodor** [Arriven/db1000n#100]
The same way we have it on GCP https://github.com/Arriven/db1000n/tree/main/terraform/gcp_expressvpn We need the infra for Azure virtual machines

**Comment by Amet13** [comment]
If someone have account on Azure I can help with writing terraform code and documentation for it

**Comment by crabulik** [comment]
Hi folks. I have created a setup for Azure Container Instances with terraform.

**Comment by Amet13** [comment]
Cool @crabulik could you make a PR?

**Comment by crabulik** [comment]
I am not so good at working with GitHub. I created a branch and tried to push it, but received the message that I do not have Write access. Do I have to perform some additional configuration?

**Comment by Amet13** [comment]
@crabulik you have to fork a repo, then clone your repo, create a branch, make changes, push to github and then create a PR to this repo.
If you have any issues with that, just send files there and I'll create a PR for you

**Comment by crabulik** [comment]
@Amet13 Thanks, created PR: https://github.com/Arriven/db1000n/pull/158

**Comment by Amet13** [comment]
Seems like can close it

**Comment by iamtodor** [comment]
@Amet13 @crabulik @Arriven shall we follow this agreement https://github.com/Arriven/db1000n/issues/146#issuecomment-1059794244 ? Can we do cross-check if the infra works from the scratch?

**Comment by Amet13** [comment]
It would be great to do a check, but without access to the cloud, it's impossible.
For those changes related to terraform we could ask for `terraform plan` output to review changes at least

**Comment by iamtodor** [comment]
@Amet13 yeah, I suppose we need to have the individual account

**Comment by Arriven** [comment]
I've created a "triage needed" label for those types of PRs to mark that we need someone other than author to check that the change is working. I'll add that label here just so that you could find it easier
