### ISSUE TITLE
[infrastructure as a code]: DigitalOcean

### ISSUE THREAD

**Issue by iamtodor** [Arriven/db1000n#101]
The same way we have it on GCP https://github.com/Arriven/db1000n/tree/main/terraform/gcp_expressvpn We need the infra for DigitalOcean droplets

**Comment by Arriven** [comment]
There was an example committed by @o-volkov to another repo when back when I wanted to use multirepo approach for this. I think we should make a PR to move it here https://github.com/db1000n-coordinators/db1000n-infra

**Comment by iamtodor** [comment]
@Arriven perhaps this article might be in use for you https://dou.ua/forums/topic/36874

**Comment by iamtodor** [comment]
relates to https://github.com/Arriven/db1000n/issues/115

**Comment by Amet13** [comment]
Implemented there: https://github.com/Arriven/db1000n/pull/142
