### ISSUE TITLE
Some proxies in proxylist have port 8010 instead of 1080

### ISSUE THREAD

**Issue by constantin-ukr** [Arriven/db1000n#109]
Into file proxylist.json

has Ip with port *8010* but general used *1080*.

"124.172.232.49:8010",
"89.108.112.1:8010",
etc.

Is it issue or correct?

**Comment by arfgdev** [comment]
could you describe a way to reproduce it?

**Comment by constantin-ukr** [comment]
As I understand the target takes from the list "proxylist.json", and if open it and find the text ":8010" you can over 20 matches. I do not say that is incorrect but should check. Thanks
