### ISSUE TITLE
Embedded VPN

### ISSUE THREAD

**Issue by ctukraine22** [Arriven/db1000n#111]
Народ, можливо варто додати вбудовану роботу через vpn?
ось у мене є приклад на docker compose https://github.com/ctukraine22/runner
суть в тому, що підіймається контейнер з vpn, і контейнер з db1000n, потім періодично vpn перепідключається.
Щоб запустити достатньо тільки дати налаштування для свого vpn, мінус в тому що із коробки провайдерів не багато підтримується

**Comment by Arriven** [comment]
Check out supervisord/ and run/ subfolders for that, feel free to open a PR if it can be further improved

**Comment by ctukraine22** [comment]
бачу вже доку додали https://github.com/Arriven/db1000n/blob/main/docs/advanced-users-and-devs.md#docker--openvpn
