### ISSUE TITLE
DigitalOcean Networking disabled error

### ISSUE THREAD

**Issue by Leta0n** [Arriven/db1000n#115]
Can I limit network usage somehow? DO keep banning my droplets because of network abuse
![IMG_FF722C95255B-1](https://user-images.githubusercontent.com/3305500/156847961-2f8709fc-4f1f-46e1-8e3b-d5fbf0cf61b6.jpeg)

**Comment by Arriven** [comment]
You can use custom config for that (see ##Configuration part of the README for reference). I'm currently working with admins to try creating a separate config to use with cloud providers that would use less traffic&CPU and more advanced attack patterns that are harder to detect. ETA is somewhere today (I will reply here once it's done)

**Comment by Leta0n** [comment]
Works great now, thanks!
