### ISSUE TITLE
Docker image is not being updated for 21 hours - new targets are not applied

### ISSUE THREAD

**Issue by dmy3tka** [Arriven/db1000n#121]
Targets config in the separate repo is being updated multiple times, but actual Docker image (that is currently running on VMs) hits outdated targets list. Please push new image ASAP.

P.S.: I can develop CI stage to build and push new image, once MR is merged. Should I start?

**Comment by Arriven** [comment]
Targets are configured outside of the image and executable (and repo because it's easier to manage that way). There is a backup config embedded into the exe but it's used as a backup if the app can't fetch remote one  and it's not meant to be updated.

There's already a CI job to build and push docker image on release.

The main reason there was no new release for 21 hours is because there were no new important updates to the codebase during that time. Almost all updates were either docs, deployment methods for clouds/platforms (mostly for experienced users), or minor code improvements that don't directly impact the functionality of the app.

There was a PR today that does bring a cool feature and I will make a release with it soon, just need to test everything first.

**Comment by Arriven** [comment]
If you see that docker image really hits outdated list I suggest checking if it can connect to the proper target list in your setup. Might be a problem there and we need to discuss/debug it separately.

**Comment by Arriven** [comment]
See https://github.com/Arriven/db1000n/issues/115 for more info on networking problems in clouds

**Comment by dmy3tka** [comment]
Ok, thanks. Checking from inside Docker. Will post the results. Use tcpdump to check packets sending.

**Comment by dmy3tka** [comment]
@Arriven can confirm, that targets are not being updated. We need to push an image each time we have a MR merged to https://github.com/db1000n-coordinators/LoadTestConfig to take a benefit of the option we are running container ` --pull always`, also we need to make sure this option works, as PID is running and I am not sure at wich moment docker will pull new `latest`.

Note, containers are running for  `41 minutes` :
`username@vm0:~$ sudo docker container ls
CONTAINER ID   IMAGE                            COMMAND    CREATED          STATUS          PORTS     NAMES
d289f665e2d9   ghcr.io/arriven/db1000n:latest   "./main"   41 minutes ago   Up 41 minutes             dreamy_gould
77b115352b0c   ghcr.io/arriven/db1000n:latest   "./main"   41 minutes ago   Up 41 minutes             agitated_jackson`

MR with new target is merged  `24 minutes ago`:
https://github.com/db1000n-coordinators/LoadTestConfig/commit/0ab67a4c1720fa1d2926ff5eddb9c0e8de8fc9ab

New target ip is not found in the container logs:

`username@vm0:~$ sudo docker logs dreamy_gould 2>&1 | grep "80.87.198.26"
username@vm0:~$`

**Comment by dmy3tka** [comment]
@Arriven ok, I see where we get conf url and update it. Can you confirm, that this loop overrides targets config each time in the container? - https://github.com/Arriven/db1000n/blob/6e515ee3f2ae6e8ff6f72417921cb60c5ed2f995/main.go#L71

And why we use such aggressive 1 minute override as we don't have such frequent changes of the conf. Let's make it reasonable 1 hour.
Thank you!

**Comment by bitshape** [comment]
@dmy3tka disagree because 1hr refresh means it will take up to an hour to get all clients refreshed. For successful results you want very quick switch of conf in order to maximize efficiency.

**Comment by dmy3tka** [comment]
> @dmy3tka disagree because 1hr refresh means it will take up to an hour to get all clients refreshed. For successful results you want very quick switch of conf in order to maximize efficiency.

Do you check how often is config changing now? 2 times a day at best. Even 1 hour is excessive refresh timeout.

We are ddosing GitHub as of now, fetching new config each minute, that can result in blockage.

**Comment by Arriven** [comment]
github is a CDN, which is designed for this specific type of load we use it for (it can and should be able to handle A LOT more load than this). This is the core of an app and I was very careful when designing it

**Comment by dmy3tka** [comment]
I amd closing this issue, as I see targets was updated, with the new image
