### ISSUE TITLE
[improvement] [win] BAT file with supervisor/guardian

### ISSUE THREAD

**Issue by 5har0varik** [Arriven/db1000n#123]
To prevent windows crash add simple supervisor in .bat file. Add .bat file to .zip package. 
For example:
```
echo starting
:start
start /w db1000n.exe
echo restarting
goto start
```

**Comment by 5har0varik** [comment]
I may create a PR, tell me what changes needed (Script location, doc changes, etc)

**Comment by Arriven** [comment]
@5har0varik PR would be nice, not sure about the location, I'd probably make the scripts/ subfolder for the script (and move install.sh there). 

Also see https://github.com/Arriven/db1000n/issues/118 for what I was thinking about structuring the docs, try to use that pattern if possible but even if you don't we can move it later. It's probably wise adding this script under instructions for technical users unless you can also make a CI job to package the script together with the executable
