### ISSUE TITLE
How use alpine/bombardier via vpn?

### ISSUE THREAD

**Issue by goodandrewsoft** [Arriven/db1000n#125]
For example how use ?
`docker run -ti --rm alpine/bombardier -c 1000 -d 3600s -l https://mil.ru`

like in https://github.com/Arriven/db1000n/blob/main/run.sh

**Comment by iamtodor** [comment]
@goodandrewsoft could you please expand your question? Basically, all you need is to turn on VPN and run `docker run ghcr.io/arriven/db1000n` or just run binaries.
You don't need `alpine/bombardier` in this implementation

**Comment by goodandrewsoft** [comment]
I know that. I'm already use db1000n via [run.sh](https://github.com/Arriven/db1000n/blob/main/run.sh)

But, sometimes, i want use `alpine/bombardier` manually and i want automate my process like in [run.sh](https://github.com/Arriven/db1000n/blob/main/run.sh)

**Comment by Arriven** [comment]
I'll assign this to @bitshape as he's the author of that implementation and knows about it more than me.

**Comment by vgoncharenko** [comment]
It's not detailed instruction, but you asked a question in the wrong repo. It's a different project from bombardier.
So I have no knowledge about db1000n or bombardier, I'm just like you - a user, but I can give you some idea of what to do:

1) add openvpn for your version of alpine/bombardier image (Add means install)
2) you will definitely need --cap-add=NET_ADMIN for your docker run command (as in run.sh)
3) mount your openvpn.config as in this example or just copy all configs you have to the running container.
4) Make OpenVPN as a service to make it autostart. Or just run it as a next command after a run of your alpine/bombardier container:
"docker exec ....... OpenVPN --config ... -auth ...."

you will probably need to restart your VPN very frequently, so just add a script like this in your image and run it through docker exec whenever you need it:

```
killall -TERM openvpn
cp -r vpn/newconfig.ovpn vpn/config.ovpn
openvpn --config vpn/config.ovpn --auth-user-pass vpn/pvpnauth --verb 6 > openvpn_log
```

Not sure which VPN you are using, but they are not very reliable, so having a log is not a bad idea.
