### ISSUE TITLE
k8s. HealthCheck

### ISSUE THREAD

**Issue by oleksdovz** [Arriven/db1000n#129]
k8s. HealthCheck
Було б добре мати для аплікухи якийсь HealthCheck
Тобто якшо пода залипла то її рестартнутию

**Comment by oleksdovz** [comment]
Крім того я знайшов такий ресурс із проксі - https://t.me/proxy_list_misha
можливо можна інтегрувати для постійного оновленння або перечитання проксі коли пода рестартує

**Comment by Amet13** [comment]
Я тестив функціонал імежду, якшо щось не так з аппкою, вона вилітає и кубер автоматично перезапскає под

**Comment by oleksdovz** [comment]
ок, добре,  там проксі http? 
як щодо файлів із  https://t.me/proxy_list_misha? вони оновлюються дуже часто.
в теорії  список http proxy  можна оновляти при старті контейнера в поді, тільки  файл із проксі має формат json а то що скачується в txt

**Comment by Arriven** [comment]
@oleksdovz to be completely honest I'm still not convinced proxies actually improve the quality of attacks as there are different opinions on the topic and most of them say that it depends. This makes me think that even if it does have a positive impact it's a low priority task. Regardless of that I think it's worth creating a separate issue to discuss this first.
