### ISSUE TITLE
 Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /root/openvpn.

### ISSUE THREAD

**Issue by deviant-studio** [Arriven/db1000n#131]
Guys, need help with running on ubuntu with custom ovpn config. i put the .ovpn into the openvpn dir. running with ./run.sh
get this error:
```
ubuntu@ip-xxxxxxxxx:~/db1000n$ sudo ./run.sh
./run.sh: 1: Bad substitution
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/Dockerfile: no such file or directory
docker: Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /root/openvpn.
See 'docker run --help'.
ubuntu@ip-xxxxxxxxx:~/db1000n$
```

**Comment by vgoncharenko** [comment]
If you add:
set -ex

at the top of run.sh, it will print you everything it's going to run. 
For some reason, it tries to use root's dir as current. Just to confirm it, add that command and try again. Maybe it's just a typo in your script.
If your code is identical with what in repo - try to run without sudo.

**Comment by Arriven** [comment]
@bitshape seems like this is your area of expertise
