### ISSUE TITLE
Network activity went down today.

### ISSUE THREAD

**Issue by vgoncharenko** [Arriven/db1000n#133]
Guys, something happened around 2:20 UTC.
my command: docker run --pull=always ghcr.io/arriven/db1000n:latest
Unfortunately, cant track if it was config changes.
<img width="1095" alt="Screen Shot 2022-03-05 at 5 36 33 AM" src="https://user-images.githubusercontent.com/10031428/156881337-0681a472-38d2-4447-900a-df349d8e64bf.png">

**Comment by Arriven** [comment]
I don't recall any config changes at that time. Need to investigate

**Comment by vgoncharenko** [comment]
I don't have vpn, btw. 
And there is no packet loss:

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        ................................................................................................
        RX packets 1403319  bytes 88604937 (84.5 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 283605121  bytes 1019714276523 (949.6 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

uptime:
 12:28:11 up 15:12,  2 users,  load average: 3.19, 2.81, 2.60

Let me know if I can help with any info.

**Comment by Arriven** [comment]
I don't have any ideas on possible cause yet so there's no ETA yet. I'll try to look into it between other critical and high priority tasks since I'm genuinely interested in finding the cause but the impact of this particular issue is relatively low. You can also play with different custom configurations in the meanwhile to try to reproduce this behavior and get more understanding on it if you have some free time

**Comment by KarboDuck** [comment]
Maybe it's just a case of new json file with smaller list of files?

If you launch db1000n with previous json (from github history) net load is still high.

`https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/0287df8617728449359bf0f71fa7d59fc4d627ed/config.json`

**Comment by dmy3tka** [comment]
> Maybe it's just a case of new json file with smaller list of sites?
> 
> 
> 
> If you launch db1000n with previous json (from github history) net load is still high.
> 
> 
> 
> `./db1000n -c https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/0287df8617728449359bf0f71fa7d59fc4d627ed/config.json`

Can you please give approximate numbers on how many targets was, and is now? I hardly believe it can go down from 1 container consumes 80% cpu core to < 10% cpu core because of a smaller target list.

**Comment by KarboDuck** [comment]
> Can you please give approximate numbers on how many targets was, and is now? I hardly believe it can go down from 1 container consumes 80% cpu core to < 10% cpu core because of a smaller target list.

First of all, my mistake, list is not smaller, just different.

I'm not sure what't the cause, maybe it is:
-different ddos protection
-some servers just not available
-different protocols(ports) generate different traffic

But I can clearly see the difference between load on cpu and network between two json files. 

In one case it is 95% load with 10-40 MB/s on my particular vps and in second case it is 5% and 10-100 KB/s. Around 5 instances of db1000n launched in both cases.

1. `./db1000n -c https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/0287df8617728449359bf0f71fa7d59fc4d627ed/config.json`
2. `./db1000n -c https://github.com/db1000n-coordinators/LoadTestConfig/blob/main/config.json`

**Comment by vgoncharenko** [comment]
Yes, I can confirm with that configuration metrics went up to where it was:
https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/0287df8617728449359bf0f71fa7d59fc4d627ed/config.json:

<img width="1087" alt="Screen Shot 2022-03-05 at 9 48 20 AM" src="https://user-images.githubusercontent.com/10031428/156890607-07f51603-a0be-4a06-ac3b-a4bb388f8865.png">

CPU as well. went up to 80-90%.

Sorry for the false alarm. I didn't know where to look for the config history.

**Comment by dmy3tka** [comment]
The difference is, that in conf with higher usage, there is a "client": {"async": "true"}. Not sure who and why removed this option from some of the targets.

**Comment by industral** [comment]
confirm, have the same issue. CPU load is down, network - almost 0

**Comment by Arriven** [comment]
I've been referencing this in other issues, but essentially more traffic doesn't always mean better DDoS. We're trying different patterns to see whether they get blocked by the target (and even source in case of cloud providers)

**Comment by dmy3tka** [comment]
@Arriven so can you confirm now that async requests are not necessary now in the current load config? In such way, we will need to run more containers per cpu core if we stick to not use async as of now.

**Comment by Arriven** [comment]
I've tried to explain some basic ideas on DDoS performance [here](https://github.com/Arriven/db1000n/issues/136)

**Comment by dmy3tka** [comment]
Ok I see that you are trying to implement here. So 1 container is sufficient for this type of attack (as unique VM IP is required). To utlilize VM resources available for me, I will sidecar some other load testing software on the VMs.

**Comment by Arriven** [comment]
I think we'll do it the following way: create a separate config file that uses advanced techniques and generate less traffic and create a separate docker image pointing to that config. Regular users will use config that maximizes traffic for now but advanced users on (especially those using VMs) will be able to use more advanced techniques if they wish so (see #153 for why this might be important)

**Comment by industral** [comment]
so was the bug fixed or not?
I just tried to pull docker and didn't see any traffic again...
config still the same..
