### ISSUE TITLE
No matching manifest for linux/arm/v7 in the manifest list entries

### ISSUE THREAD

**Issue by YuriyKu** [Arriven/db1000n#137]
Hello,
I'm trying to run db1000n on raspberry pi3 with next error:

Unable to find image 'ghcr.io/arriven/db1000n:latest' locally
latest: Pulling from arriven/db1000n
docker: no matching manifest for linux/arm/v7 in the manifest list entries.

My system is:
$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Could you please resolve this problem from your side?

**Comment by iamtodor** [comment]
@YuriyKu take a look on https://github.com/Arriven/db1000n/issues/116

**Comment by Amet13** [comment]
Support for arm/v7 already in master.
In the next release, it will be deployed.
Keep following https://github.com/Arriven/db1000n/pkgs/container/db1000n

**Comment by Amet13** [comment]
@YuriyKu please try to pull the latest image again, it should work. Introduced arm/v7 support in 0.5.13

<img width="764" alt="Screenshot 2022-03-06 at 12 04 37" src="https://user-images.githubusercontent.com/5184847/156918470-061c3483-2e07-499f-9024-b6f5d4adb60d.png">

**Comment by YuriyKu** [comment]
Hello, it works now. Thanks a lot.

**Comment by YuriyKu** [comment]
Issue has been resolved. Thanks. Have a nice day.
