### ISSUE TITLE
Incorrect color output in default windows command prompt

### ISSUE THREAD

**Issue by MAKMED1337** [Arriven/db1000n#145]
Logs looks bad at windows 
![image](https://user-images.githubusercontent.com/50710486/156887852-aeb78999-8021-4cd5-9fc0-fc6b5498649f.png)

**Comment by Devaniti** [comment]
You can use Windows Terminal to get better output

**Comment by Amet13** [comment]
@Devaniti could you reproduce it on Windows? Unfortunately don't use it

**Comment by Devaniti** [comment]
@Amet13 Yes, it's reproducible with default "cmd" console
But with new "Windows Terminal" it works as expected

**Comment by Amet13** [comment]
Seems like not an issue then?

**Comment by Devaniti** [comment]
Windows Terminal is only available on Windows 10
But I'd say it's minor issue either way

**Comment by iamtodor** [comment]
@Devaniti @Amet13 @MAKMED1337 do we have this issue while running binaries? what is the proper way to run it in Windows 10 then? I'd suggest to add a mention in our doc how to run it in Windows 10

**Comment by Amet13** [comment]
@iamtodor I would say it works properly on the screenshot except for colors in default Terminal 😄

**Comment by iamtodor** [comment]
@Amet13 okay, then I think we are free to close this issue right? Or we can leave it as open but change the title in order to not confuse ourselves

**Comment by Devaniti** [comment]
I'd change the title to something like "Incorrect color output in default windows command prompt"

**Comment by iamtodor** [comment]
@Devaniti fully agrees! 

Only @MAKMED1337 and @Arriven are able to change the title or are there some people who have the rights and access?
cc @Amet13

**Comment by pashagolub** [comment]
Use PowerShell instead https://github.com/PowerShell/PowerShell
