### ISSUE TITLE
gcp-installation-ua.md  not working 

### ISSUE THREAD

**Issue by sergnochevny** [Arriven/db1000n#146]
cloud instance becomes unavailable after running openvpn3.sh from gcp-installation-ua.md
checked on DO and GCP

**Comment by Amet13** [comment]
@Arriven @iamtodor as I mentioned before in this comment: https://github.com/Arriven/db1000n/issues/118#issuecomment-1059743438 this doc looks a bit strange. Can we find an author of it to review doc?
Or we can delete it to not to confuse people with it

**Comment by iamtodor** [comment]
@Amet13 @Arriven as I suggested before let's keep only English version

**Comment by Arriven** [comment]
Let's find the author first, if we get no feedback in 12 hours we can delete it but there's no rush yet since these guides expect at least some level of technical expertise which might be enough to get through even with errors in the guide

**Comment by Arriven** [comment]
I think we should also enforce the rule where at least two other people should validate new guides/big changes to guides and different scripts/terraform/k8s_manifests/docker-compose files which we don't have CI jobs for yet. I'll create a separate label for that
