### ISSUE TITLE
Next Milestone | BLOCK

### ISSUE THREAD

**Issue by bmirnoff** [Arriven/db1000n#165]
This is a strategic post. 

I think next milestone might be a shift from chaos dos to a situation when doing it is profitable or makes achievements.  
This might be done like a blockchain. Proposal:

Layer 2 tokens that might be minted during the execution of attacks. 
For instance
- each successful attack response is a nonce in PoW algo
- signed hash of a config json 
- some hash from prev block 

Resulted minted block gives a reward as a token. Might be a unique achievement that actually never happened again. 

Important tech details:
- participant registered by anon acc for layer 1 chain
- token minted for participant account
- **json config is the source of truth. Must be signed by the private key.**
- **json changes might be controlled by DAO that rules this Layer 2 event** 
- **DAO must have a kill button that finished this event.** 

```
contract DAO {
    // emit new changes that spreaded by w3 for all participants 
    emitConfigChanges( ... )

    // End of Game, so all minting is not allowed anymore. This IS IMPORTANT!!!
    endOfGame(  )

    // mint next toket to the account
   // @input  attack hash evidances, a.k.a. hash of conf+nonce+prev.hash.
   // @result on consensus, mint a token to participant 
    mint(  ""  )
}
```

Block actually can be a small string, just with required hashes to be able to get consensus. 

Participants: 
- has an option to be launched as an anonymized wallet within a chain (or even generate a new one) So, mint actions are connected with this wallet
- run success attacks
- based on config hash, success attack responses and another stuff get a hash that can be used for mint. Logic of minting based on contract logic internally 
- next block tried to be minted via contract (if there are a consensus on a chain for the proposed block, the participant receive a token)

NOTE: 

- this is not a chain in true meaning, but an event that is controlled via DAO with a reward for participants that works via w3 with a chain
- it **must** be controlled by DAO. This thing need to be unique (never happened again) and controlled as can decrease a  blockchain reputation
- the chain must has chip transactions and has w3 support. 

Maybe some input from another blockchain guys here is needed. 

cc: @Arriven

**Comment by bmirnoff** [comment]
@Arriven what do you think? 

My vision

-  it might be a layer 2 thing. Event not a true chain by a client that works with a chain based on w3 via smartcontract of a chan. 
- it **must** be controlled by DAO. This thing need to be unique (never happened again) and controlled as can decrease a  blockchain reputation
- chain must has chip transactions and has w3 support

**Comment by bmirnoff** [comment]
Goals:
- gamification for all remaining world 
- maintain **interest** 

I think these are important actions and effects from each of them hard to estimate.

**Comment by bmirnoff** [comment]
Issues:
- tokens might be a part of illegal activity, but who cares now? 
- impact on the chain community, also hard to estimate. There are a lot of scum there, so the key point is that this process has the end where all DAO members voted for its stop.

**Comment by Arriven** [comment]
We're currently forced to work in a gray hat area by this awful situation. Minting tokens with this would turn this into black hat. I want to turn it into white hat to be used by security professional to benchmark their DDoS protection. The code is distributed under MIT license so I can't stop you from doing your own fork and pursuing your goals but I'd rather you not do it
