### ISSUE TITLE
DDoS effectiveness is not directly tied to the amount of traffic generated

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#170]
The app is configurable to generate set amount of traffic (controlled by the number of targets, their type, and attack interval for each of them). The main reason it works that way is because there are two main types of ddos:

- Straightforward load generation (easy to implement, easy to defend from) - as effective as the amount of raw traffic you can generate

- Actual denial of service that aims to remain as undetected as possible by simulating plausible traffic and hitting concrete vulnerabilities in the target (or targets). This type of ddos doesn't require a lot of traffic and thus is mostly limited by the amount of clients generating this type of load (or rather unique IPs)

A lot of people are worried about this app generating low amount of traffic so we need to add a section to the docs explaining this reasoning to prevent questions

**Comment by Arriven** [comment]
@Amet13 @iamtodor tagging you here

**Comment by Amet13** [comment]
My proposal is to create a separate document called `FAQ.md` (for non-technical, let's say questions).

In this document add information in format `question` - `answer`.

For example, issues related to billing in clouds, DDoS efficiency, etc

**Comment by Arriven** [comment]
I'm also adding another docker image which points to another config file to be used by advanced users that understand this (especially in clouds). We'll probably need to update advanced users docs with it as soon as it's ready. I'll ask someone to change default config to use more straightforward jobs couple hours after that in order to give people time to safely switch their clusters

**Comment by iamtodor** [comment]
@Amet13 I also have something to add in FAQ

**Comment by iamtodor** [comment]
as just general question/answer
