### ISSUE TITLE
fix ip

### ISSUE THREAD

**Issue by krotoveugene** [Arriven/db1000n#177]
https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json
```{
            "type": "http",
            "args": {
                "method": "GET",
                "path": "https://1185.114.138.220:443", !!!!!!! 
                "interval_ms": 1
            }
        },
```

**Comment by krotoveugene** [comment]
@arfgdev need to fix typo in IP - https://1185.114.138.220:443

**Comment by 5har0varik** [comment]
I may create RP but cant locate file =\

**Comment by mxmCherry** [comment]
Already PR-ed in relevant repo, even twice:

- https://github.com/db1000n-coordinators/LoadTestConfig/pull/10
- https://github.com/db1000n-coordinators/LoadTestConfig/pull/9

**Comment by Arriven** [comment]
This was fixed 5 hours ago, thanks for heads up though!
