### ISSUE TITLE
better list of resources to attack.

### ISSUE THREAD

**Issue by zmitry** [Arriven/db1000n#18]
gather list from different places https://t.me/itarmyofukraine2022.

**Comment by Arriven** [comment]
You can also go ahead and add those targets through a PR here https://github.com/db1000n-coordinators/LoadTestConfig

**Comment by sanohin** [comment]
`https://api.mosgorpass.ru/v8.2/stop` - query all bus stops
`https://api.mosgorpass.ru/v8.2/stop/{{ stop_id }}` - `stop_id` from the list from the prev endpoint
