### ISSUE TITLE
 The app doesn't seem to generate any traffic, please contact your admin

### ISSUE THREAD

**Issue by ivan-huligan** [Arriven/db1000n#182]
After updating from the release v0.5.13 to the release v0.5.14 the error message constantly appears
` The app doesn't seem to generate any traffic, please contact your admin`

**Comment by su-hs** [comment]
I confirm, I also see this warning.

**Comment by mxmCherry** [comment]
Seems to be a problem with metrics tracking. The app itself seem to be working fine (traced it properly - it still generates traffic).

**Comment by mxmCherry** [comment]
UPD: actually nope, metrics are "fine" (metric design choices are questionable, but they kinda work). What actually happens is:

- metrics store approx bytes written only for last second measured
- so if there was no traffic for the last second within the minute (config refresh interval)
- it'll return 0 and will write a "The app doesn't seem to generate any traffic, please contact your admin" warning

This doesn't really affect anything.

Most likely, either resources are now down or your (VPN) IP is already blocked on the "recipient" side. So you cannot connect to the host often enough - connection attempts are just timing out.

**Comment by Arriven** [comment]
Yeah, metrics were added rather quickly with focus on showing users at least something (remember, the app is just a bit more than a week old). I think I'll change it to track overall traffic generated instead of doing the per second thing until I get time to implement something more robust

**Comment by mxmCherry** [comment]
Right now my question is "**shoud we decrease default timeout in the program? I suggest 1-5 seconds default, not more**" so if load-testing target doesn't hold the load app from testing other targets.

Async=true could help with "blocking", but that's a sure way to OOM (uncontrolled `go func()` spawned each ~1s with 90s timeout.

---

Metrics-impl-wise:

I suggest not to reinvent the wheel and take smth that already exists, for example: https://pkg.go.dev/github.com/bsm/instruments (definitely there are more options).

But anyway, swapping metrics impl right now is just bikeshedding, doesn't add much value.

**Comment by Arriven** [comment]
For async=true ideally we'd implement sending http frames into packetgen or use something similar to send http frames without waiting for response in a more efficient manner.
We need to consider ROI when implementing features here. I've spent roughly 30 minutes to implement metrics the way they are done now and I know I need only 10 more minutes near my laptop to make it work in a more stable manner. I estimate integrating more robust metrics framework would take at least couple hours and while it would be a good solution - the benefit from it doesn't cost that time at the current stage of the project (there are more high priority issues related to core functionality of the app). But that doesn't mean that anyone else can't go and integrate those metrics instead if they have free time
