### ISSUE TITLE
Online config won't update when using proxychains-ng

### ISSUE THREAD

**Issue by SomalianCoolhacker** [Arriven/db1000n#183]
Hi, my VM (Ubuntu 20.04 LTS) can't reach online config using proxychains (country RU, socks4/5 proxies):
> ~$: sudo proxychains ./db1000n
> [WARN] Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": dial tcp 224.0.0.1:443: connect: network is unreachable
> [WARN] Could not load new config, proceeding with backupConfig

I'm using proxychains as an alternative to VPN on my VM. Without it, attacks won't generate any traffic usually.

P.S: I know there's an implementation of proxy in db1000n, but as far as I know, it uses random_chain instead of dynamic_chain, which means if it lands on a dead proxy, it will fail to proceed further.

**Comment by Arriven** [comment]
You can download the config and pass the path to it via `-c path/to/file.json` as a workaround

**Comment by Somartu** [comment]
Thanks!
If I'll create a script that redownloads config occasionally, will an already running db1000n update targets as well?

**Comment by Arriven** [comment]
db1000n updates targets automatically regardless whether it's pointed at remote or local config. You should even be able to do something like `-c https://remote/config/url,path/to/local/config`- that way it'll try fetching remote config first and backup to file if remote one fails

**Comment by Arriven** [comment]
Closing this as there are already multiple solutions like the one in `examples/docker/static-docker-compose.yml`
