### ISSUE TITLE
[Discussion] Providing certain restricted access to the repo

### ISSUE THREAD

**Issue by iamtodor** [Arriven/db1000n#189]
As a follow up to the PR https://github.com/Arriven/db1000n/pull/187
Please take a look at the docs:
-  https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-teams-and-people-with-access-to-your-repository 
- https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization

Currently, there is a mess in Issues. Some of them need to be closed / renamed / labeled / linked / marked as duplicate / marked as needs to have more details to investigate / etc.

Can I suggest assigning `Triage` for my account to be able to maintain docs / issues / PRs?

cc @Amet13 @Arriven @su-hs

**Comment by dmy3tka** [comment]
Please note paths how this MR was submitted https://github.com/db1000n-coordinators/LoadTestConfig/commit/b8886cce0aa5787260046e4acbab35832a347ec5

It broke async load once again! We can have more of these.

**Comment by iamtodor** [comment]
@dmy3tka I'm not sure whether your comment relates to the topic

**Comment by synapse-unix** [comment]
@iamtodor what is intend of your activity, to limit possibility of merging MRs that broke things from unreliable sources? As you can check, the merged commit above removed async, that degrades CPU utilization of the application from 100% to 1%, by removing async. So it is one of the examples of such harmful changes.

**Comment by iamtodor** [comment]
@synapse-unix `what is intend of your activity, to limit the possibility of merging MRs that broke things from unreliable sources?` - actually no. I would like to have the access to issues / PRs. 
I am not going to have merge power.

**Comment by Arriven** [comment]
@iamtodor it looks like personal repos don't support triage access. I'd need to create an organization and move the repo there to be able to manage access at that level. Let's see if that is required in a couple days

**Comment by iamtodor** [comment]
@Arriven I cannot accept the invitation
<img width="620" alt="image" src="https://user-images.githubusercontent.com/12586108/156991518-e9b0e19b-b208-43bf-b23a-feb23cdfd7b2.png">
