### ISSUE TITLE
Gather list of free vpns and best vpn locations to use(ideally russian)

### ISSUE THREAD

**Issue by zmitry** [Arriven/db1000n#19]
ideally it would be good to spin up russian vpn for attacks

**Comment by zmitry** [comment]
tunnel bear gives 10gb of traffic for free
https://www.tunnelbear.com/ 

swiss and Bulgaria seems to work fine for russia.

**Comment by sanohin** [comment]
Free with a promocode
https://my.clearvpn.com/promo/redeem?code=SAVEUKRAINE

**Comment by maxkoshevoi** [comment]
[UrbanVPN](https://www.urban-vpn.com/) is also a possible candidate. It worked well before, needs validation if it works now

**Comment by horodchukanton** [comment]
windscribe 30gb with promo ПИЗДЕЦ

**Comment by iamtodor** [comment]
the issue can be closed as it was implemented in https://github.com/Arriven/db1000n/pull/94

**Comment by iamtodor** [comment]
@Arriven please close the issue as it was implemented in https://github.com/Arriven/db1000n/pull/94

**Comment by iamtodor** [comment]
update: was re-implemented in https://github.com/Arriven/db1000n/pull/104 @Arriven

**Comment by iamtodor** [comment]
@zmitry @Arriven @Amet13 please close this issue
