### ISSUE TITLE
docker compose random VPM

### ISSUE THREAD

**Issue by industral** [Arriven/db1000n#190]
So far I see in docker compose we have predefined VPN endpoints

https://github.com/Arriven/db1000n/blob/main/docker-compose.yml `VPN_CONFIG_FILE: provider01.endpoint01.conf`

I like the approach you did when you provide openvpn folder and it select VPN randomly.
it might be very useful to restart docker let's say each 15min via cron and it will select another IP due to such approach.

Can we return such approach back?

**Comment by bitshape** [comment]
@industral I'm working on this, PR incoming in a bit

**Comment by bitshape** [comment]
@industral https://github.com/Arriven/db1000n/pull/193
