### ISSUE TITLE
Update tutorial on Google Drive

### ISSUE THREAD

**Issue by Amet13** [Arriven/db1000n#191]
This doc was mentioned in the large telegram channel: https://docs.google.com/document/d/1onvSrNu1FnNKDHD0Mtwf0KoOSuZJOClHqHOs5cu20Mc/edit#

If someone has access to it, it would be great to update it, at least links to binaries

@Arriven fyi

**Comment by iamtodor** [comment]
@Amet13 I see no point to maintain this doc as well. We have two READMEs:
- https://github.com/Arriven/db1000n/blob/main/README.md
- https://github.com/Arriven/db1000n/blob/main/README-ua.md

I am strongly against maintaining even more resources. I would propose where we had links to Google Docs update links to READMEs.

Having 2 descriptive and extensive READMEs is more than enough.

Maybe we need to put the information directly in the docs such as the info has been moved to the READMEs. Please follow it

**Comment by Amet13** [comment]
agree with that

**Comment by iamtodor** [comment]
@Amet13 have any actions been applied? I see that the content of the file wasn't changed.
@Arriven let's update the doc itself by providing links to READMEs
Until that I suggest don't close this issue

**Comment by Amet13** [comment]
AFAIK, we don't have access to this doc.
Seems like someone just copy-pasted readme some time ago and we can't help with updating or deleting this doc

**Comment by iamtodor** [comment]
@Amet13 hmmmm.. I thought @Arriven is the author of the doc, no? :D

**Comment by Amet13** [comment]
I don't know, as I said, I found link to this doc in the large telegram channel
