### ISSUE TITLE
Figure out a way to run packetgen without root permissions

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#200]
Currently packetgen jobs send this type of message when you run the program under regular user
`2022/03/07 06:51:38.219638 packetgen.go:77: Error sending packet: listen ip4:tcp 0.0.0.0: socket: operation not permitted`
This is happening because it needs raw connection in order to be able to customize ethernet, ip, and tcp/udp frames. It's not a huge issue but would be nice to know if there's a way to workaround that somehow

**Comment by Boostro** [comment]
I have a similar issue.
`packetgen.go:65: Error sending packet: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.`

**Comment by neuton** [comment]
I believe the only alternative way (under Linux) is to set CAP_NET_RAW capability on the executable, as mentioned by answers here https://stackoverflow.com/questions/20763039/creating-raw-socket-in-python-without-root-privileges
