### ISSUE TITLE
If Russia blocks github, config won't load when using RU VPN

### ISSUE THREAD

**Issue by Devaniti** [Arriven/db1000n#204]
We need to make some kind of mirror, for RU VPN users

**Comment by Devaniti** [comment]
Preferably, it should be some large HTTPS website, so they can't easily block it

**Comment by Arriven** [comment]
This is a good idea. I'll add that the app can already be configured to fetch config from multiple sources so the only part we need is to get that mirror up and running

**Comment by Devaniti** [comment]
I'll try to do it

**Comment by bitshape** [comment]
We could setup AWS Route 53-backed DNS with really low TTL (5 seconds) with Geo DNS. If request comes from RU, we route it to a known good mirror that can be accessed through RU VPN. If that mirror gets blocked, we find another one and everything gets refreshed in ~5 sec.

**Comment by Devaniti** [comment]
@bitshape I'll setup mirror for git repo on another hosting, and you can setup AWS mirror
more mirrors is good, just in case

**Comment by bitshape** [comment]
@Devaniti I've looked into setting this up on AWS S3 as mirror and if Docker image stats are any indication, it's going to cost prohibitive for me to run (~$3.5K/month).

**Comment by Devaniti** [comment]
@bitshape that's sad. Hopefully, small percentage of people will need to use that mirror, and they will load small config file. But they will reload it every minute. So it's hard to know for sure that it won't cost a fortune.
