### ISSUE TITLE
I have created DO terraform module, but I can't make pull requests.

### ISSUE THREAD

**Issue by dddbbbsss** [Arriven/db1000n#210]
This module creates a number of servers in each of provided region. If you set count = 2 and regions = ["nyc1", "nyc2", "nyc3"] this will create six servers total. Two servers in each of regions.
[repo](https://github.com/dddbbbsss/terraform_db1000n)

**Comment by sivillakonski** [comment]
Hi @dddbbbsss, thanks for the contribution!
Can you please create a fork of this repo, add your changes, and later just create a PR request from your fork?

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

It's not super handy, but a very common approach for the Github-based projects :)
