### ISSUE TITLE
Failed to fetch config

### ISSUE THREAD

**Issue by pashagolub** [Arriven/db1000n#217]
The latest 0.5.15 built from sources with go1.17.6 windows/amd64 produces a lot of errors:
```
...
2022/03/07 17:57:30.176608 runner.go:160: Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": dial tcp 185.199.108.133:443: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
2022/03/07 17:57:30.176770 runner.go:78: Could not load new config, proceeding with last known good config
...
```

The initial config seems to be loaded successfully.

**Comment by freey0urmind** [comment]
The same issue on Ubuntu 18.04. At the moment the script is generating much less trafic as it was earlier.

**Comment by industral** [comment]
yeah had the same as well, and agree on traffic. But it might be `-advanced` image, that try to work in stealth mode.
In my case traffic is about 3-12Kb when app show avg traffic. It's super low, in compare as was before 5GB/min.
But I believe it allows to work in "safe" mode and not be detected as DDoS.

**Comment by vladdancer** [comment]
@industral , I'm using avanced image and having similar problem:
```
Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json": 
Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json": 
net/http: TLS handshake timeout
```
Doing a simple curl to download this file works fine (with, without VPN).
The app is running from simple shell script.

Any suggestions how to fix it?

Other errors having with enabled VPN (Amsterdam, Sweden), provider expressvpn:
- `countrychecker.go:31: Can't check users country.`
- `Body' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[login:{{ random_uuid }} password:{{- random_int -}}{{- random_int -}}{{- random_int -}}{{- random_int -}}]`
- `packetgen.go:65: Error sending packet: write ip 0.0.0.0->0.84.166.243: sendmsg: invalid argument`

**Comment by industral** [comment]
What I saw when it happened, because db1000n container started and openvpn container failed at some point.
And also tried to check connection from container and it was without internet connection.
But after some time - issue fixed, and internet appear.
Maybe it was transient issue, IDK.

Frankly all that openvpn switching is difficult and make only sense if you use async (not advanced) config which generates tons of traffic.
Otherwise using advanced config - it generate so little traffic and seems like works in stealth mode, that possibility that your IP will be banned due to DDoS - low.

Hence, I just switched to AWS, and run many instances - each of them has its own IP and never will be banned due to difficulty to detect such low traffic.

And a price will be the same as order vps/dedicated server for 1 day...

I think that's the most optimal way so far.

**Comment by bitshape** [comment]
Docker VPN container already has health check to see if Internet is up:

https://github.com/wfg/docker-openvpn-client/blob/master/Dockerfile#L26

I'll investigate VPN angle as well a bit more as time permits.

**Comment by Arriven** [comment]
> - `Body' expected type 'string', got unconvertible type 'map[string]interface {}', value: 'map[login:{{ random_uuid }} password:{{- random_int -}}{{- random_int -}}{{- random_int -}}{{- random_int -}}]`
Oops, that one is actually new, although I thought nobody is using that particular functionality but let me check

**Comment by bitshape** [comment]
```diff
diff --git a/main.go b/main.go
index 37207e4..1491922 100644
--- a/main.go
+++ b/main.go
@@ -75,6 +75,9 @@ func main() {
                templates.SetProxiesUrl(proxiesURL)
        }

+       time.Sleep(10 * time.Second);
+
        go utils.CheckCountry([]string{"Ukraine"})

        r, err := runner.New(&runner.Config{
```

So my anecdotal experience here is that simply sleeping before doing any work solves this issue (docker with VPN). Problem is relatively easy to verify if you connect to relatively slow VPN.

I'm going to keep looking.

**Comment by freey0urmind** [comment]
Even though the fetch line is till there I believe the situation is better now but I am kinda confused )) 
```
2022/03/09 19:21:20.691044 config.go:82: **Could not load new config, proceeding with the backup one**
2022/03/09 19:21:20.691060 config.go:93: **New config received, applying**
2022/03/09 19:21:20.690975 countrychecker.go:31: Can't check users country. Please manually check that VPN is enabled or that you have non Ukrainian IP address.
2022/03/09 19:21:21.492809 config.go:100: Decrypted config
```

**Comment by freey0urmind** [comment]
The fetch error line has gone. Thank you!

**Comment by bitshape** [comment]
I've opened two PRs that might help with this issue or at least make it happen less often:

https://github.com/Arriven/db1000n/pull/275
https://github.com/Arriven/db1000n/pull/274

**Comment by vladdancer** [comment]
Thank you @bitshape, @Arriven.
But I'm still having the same erros from the above. The only issue that has gone:
`Body' expected type 'string', got unconvertible type 'map[string]interface `

The next log sounds strange for me:
```
config.go:82: Could not load new config, proceeding with the backup one
config.go:93: New config received, applying
```

**Comment by vladdancer** [comment]
Thank you @Arriven .
Yeah, I've updated docker image to the lates 0.6.5.
But still having error with fetching advanced config, when enabled VPN outside of container.

**Comment by bitshape** [comment]
@vladdancer can you share relevant logs?

**Comment by vladdancer** [comment]
I'm running the next script:
```
expressvpn disconnect
docker stop $(docker ps -a -q)
docker pull ghcr.io/arriven/db1000n-advanced:latest
expressvpn connect smart
sleep 10
docker run --rm ghcr.io/arriven/db1000n-advanced
```

```
2022/03/10 20:12:49.720992 countrychecker.go:31: Can't check users country. Please manually check that VPN is enabled or that you have non Ukrainian IP address.
2022/03/10 20:12:49.721032 config.go:32: Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json": net/http: TLS handshake timeout
2022/03/10 20:12:49.721081 config.go:86: Could not load new config, proceeding with the backup one
2022/03/10 20:12:49.721089 config.go:97: New config received, applying
2022/03/10 20:12:50.613787 config.go:104: Decrypted config
2022/03/10 20:12:50.614901 runner.go:129: 24 job instances (re)started
....
2022/03/10 20:12:50.619512 http.go:137: Attacking https://online.sberbank.ru/login
2022/03/10 20:12:50.620724 packetgen.go:58: Attacking online.sberbank.ru:443
2022/03/10 20:13:15.529304 packetgen.go:89: Error sending packet: write ip 0.0.0.0->226.63.4.181: sendmsg: invalid argument
2022/03/10 20:13:15.529371 runner.go:118: error running job: write ip 0.0.0.0->226.63.4.181: sendmsg: invalid argument
2022/03/10 20:13:49.769267 runner.go:168: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/10 20:13:49.769955 runner.go:169: Attack is successful! Russian warship, go fuck yourself!
2022/03/10 20:13:49.769980 runner.go:170: The app has generated approximately 103798838 bytes of traffic
2022/03/10 20:13:59.869378 config.go:32: Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json": net/http: TLS handshake timeout
2022/03/10 20:13:59.869528 config.go:83: Could not load new config, proceeding with the last known good one
2022/03/10 20:13:59.869581 config.go:92: The config has not changed. Keep calm and carry on!
```

**Comment by freey0urmind** [comment]
I was too fast saying the fetch issue had gone. Actually it does not occur just when I am vpn connected to one specific country. When I am connected to all others the issue occurs.
`2022/03/10 23:20:25.964203 config.go:32: Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Comment by vladdancer** [comment]
Ok, I think as a workaround for fetching config I should try to download it manualy with disabled vpn and then run db1000n container with overwritten entry point to specify path to the config.

```
vpn disconnect
docker stop $(docker ps -a -q)
docker pull ghcr.io/arriven/db1000n-advanced:latest
curl  https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json -o config.adv.json
vpn connect

sleep 10

docker run --rm  -v "$(pwd)"/config.adv.json:/usr/src/app/config.adv.json \
  --entrypoint='/usr/src/app/db1000n' \
  ghcr.io/arriven/db1000n-advanced \
  -c /usr/src/app/config.adv.json
```

I've tried to run the above but it seems I'm not very familiar with docker to mount host config properly into docker.
```
config.go:32: Failed to fetch config from "/usr/src/app/config.adv.json": Get "/usr/src/app/config.adv.json": unsupported protocol scheme ""
2022/03/12 22:06:53.188704 config.go:86: Could not load new config, proceeding with the backup one
2022/03/12 22:06:53.188711 config.go:97: New config received, applying
2022/03/12 22:06:54.077462 config.go:104: Decrypted config
2022/03/12 22:06:54.078453 runner.go:131: 24 job instances (re)started
2022/03/12 22:06:54.078495 http.go:128: Attacking <nil>
2022/03/12 22:06:54.078641 http.go:128: Attacking <nil>
2022/03/12 22:06:54.078771 http.go:128: Attacking <nil>
2022/03/12 22:06:54.078931 http.go:128: Attacking <nil>
```
Could someone help with that?

**Comment by Arriven** [comment]
@vladdancer that one might actually be a bug. The way I did file vs url checking is probably detecting full path as some malformed protocol, I'll make a fix shortly, meanwhile you can try that same script but providing relative path to the config

**Comment by Arriven** [comment]
@vladdancer I've merged a fix for that particular problem, try using `db1000n-beta` image to confirm it works with your setup with passing config to the program via docker volume

**Comment by bitshape** [comment]
@vladdancer i’m working on Docker solution that should fix this hopefully for good.

**Comment by vladdancer** [comment]
Thank you Arriven! It was not obvious to get right app path for the beta image, but I've managed it :)
Thanks god there is a tool https://github.com/wagoodman/dive and `docker inspect`

```
docker run --rm  -v "$(pwd)"/config.adv.json:/ko-app/config.adv.json --entrypoint='/ko-app/db1000n' ghcr.io/arriven/db1000n-beta -c /ko-app/config.adv.json
```

I confirm that next errors are gone:
- 2022/03/12 22:06:54.078495 http.go:128: Attacking <nil>
- config.go:32: Failed to fetch config from "/usr/src/app/config.adv.json": Get "/usr/src/app/config.adv.json": unsupported protocol scheme ""

Just a note, didi you know why `docker image ls` reports that `ghcr.io/arriven/db1000n-beta` cretated 52 years ago?

@bitshape I'm keen to try it!

**Comment by vladdancer** [comment]
Guys, you're so fast with recent updates) I got broken db1000n.
Any ideas why the app doesn't generate traffic anymore?


```
docker run --rm  -v "$(pwd)"/config.adv.json:/ko-app/config.adv.json \
--entrypoint='/ko-app/db1000n' ghcr.io/arriven/db1000n-beta \
-c /ko-app/config.adv.json \
--prometheus_on=false \
--country-list=""
....
main.go:54: DB1000n [Version: v0.0.1][PID=1]
config.go:60: Loading config from "/ko-app/config.adv.json"
config.go:135: Can't decrypt config
runner.go:160: The app doesn't seem to generate any traffic, please contact your admin
```

I've used flags `country-list, prometheus_on` to prevent checking country and statistics, since it doesn't work for me. The funny thing the `curl ifconfig.me` shows correct IP (of VPN).

```
countrychecker.go:44: Can't check users country. Please manually check that VPN is enabled or that you have non Ukrainian IP address.
```

**Comment by Arriven** [comment]
@vladdancer the problem was this line `config.go:135: Can't decrypt config`
beta images don't contain proper encryption keys and at the time whole config was encrypted. I've changed it to encrypt only specific jobs that require the element of surprise to be more effective so the beta image will work but it won't be able to run those encrypted jobs. Also you shouldn't be using beta image full-time, it's a lot less stable than regular ones (and even regular ones are not stable enough yet) so since the initial feature of this discussion is already released I'd advise you switching back to the regular image

**Comment by Arriven** [comment]
unless you want to help testing out new functionality, but even then it's better running most of your instances on regular images and only 1 or 2 on beta to be able to spot issues in new features before they get released
