### ISSUE TITLE
terraform aws use spot instances 

### ISSUE THREAD

**Issue by industral** [Arriven/db1000n#222]
So far we pay for on demand instances, and it takes money.
Using spot instances - cheeper and allow to run more server for the same money :)

Need spot instances configuration for aws.
Thanks :)

**Comment by iamtodor** [comment]
@industral @Arriven wasn't it implemented here https://github.com/Arriven/db1000n/pull/213 ?

**Comment by industral** [comment]
Many thanks! You guys do changes too fast :)
