### ISSUE TITLE
eats up 2 GB of RAM in ~2 mins and crashes with OOM error

### ISSUE THREAD

**Issue by nonchalant-enthusiast** [Arriven/db1000n#225]
behavior is unstable on 2GB VPS, Ubuntu 20.04 using latest docker v0.15.8. while generating approx. the same amount of traffic

![Screenshot (31)](https://user-images.githubusercontent.com/27624986/157137074-935b5e6f-aa0c-4de9-a431-9744b6a78119.png)

![Screenshot (32)](https://user-images.githubusercontent.com/27624986/157137105-dcf85aea-6ec1-43b0-a72e-58abc9a5a3e5.png)
each spike corresponds to the deployment and consequent crash

v0.15.4 seems to be stable

**Comment by sivillakonski** [comment]
@nonchalant-enthusiast , thanks for submitting the issue. I didn't use the profiler this time, so there might be other memory leaks around. Please report if you keep observing any memory related issues.

By the way, what tool do you use to see the memory consumption in this fancy way? Is it Cockpit?

**Comment by Arriven** [comment]
I think the issue might be deeper than the one addressed in the referenced PR. I also don't experience it running latest code as a regular executable but do experience it in docker. Looking at it

**Comment by Arriven** [comment]
ok, I've found what it is, poked the author and fixing now
