### ISSUE TITLE
The app doesn't seem to generate any traffic

### ISSUE THREAD

**Issue by freey0urmind** [Arriven/db1000n#247]
2022/03/08 23:04:12.337415 runner.go:157: The app doesn't seem to generate any traffic, please contact your admin

2022/03/08 23:04:42.338450 config.go:29: Failed to fetch config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": Get "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json": dial tcp: i/o timeout

2022/03/08 23:04:42.338493 config.go:77: Could not load new config, proceeding with the last known good one

2022/03/08 23:04:42.338504 config.go:86: The config has not changed. Keep calm and carry on!

2022/03/08 23:05:12.339786 runner.go:157: The app doesn't seem to generate any traffic, please contact your admin

**Comment by Arriven** [comment]
Can you check if you can download that config manually via curl from the corresponding instance? `curl https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json` should be enough

**Comment by freey0urmind** [comment]
> 

Yes, I can download. The script was displayed directly in the terminal window.

**Comment by freey0urmind** [comment]
One more thing the line " The app doesn't seem to generate any traffic, please contact your admin" is not coming anymore, instead I am getting the "The app has generated approximately XXXXXXXXXX bytes of traffic" which is good I believe.
