### ISSUE TITLE
Error looking up DNS / Error sending packet

### ISSUE THREAD

**Issue by freey0urmind** [Arriven/db1000n#248]
2022/03/08 23:13:57.518243 utils.go:153: Error looking up DNS: lookup online.sberbank.ru on 24.200.210.241:53: read udp 172.17.0.2:41928->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.518279 packetgen.go:65: Error sending packet: lookup online.sberbank.ru on 24.200.210.241:53: read udp 172.17.0.2:41928->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.518291 utils.go:153: Error looking up DNS: lookup rg.ru on 24.200.210.241:53: read udp 172.17.0.2:46041->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.518314 packetgen.go:65: Error sending packet: lookup rg.ru on 24.200.210.241:53: read udp 172.17.0.2:46041->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.518302 utils.go:153: Error looking up DNS: lookup online.sberbank.ru on 24.200.210.241:53: read udp 172.17.0.2:41928->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.518372 packetgen.go:65: Error sending packet: lookup online.sberbank.ru on 24.200.210.241:53: read udp 172.17.0.2:41928->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.518287 utils.go:153: Error looking up DNS: lookup rg.ru on 24.200.210.241:53: read udp 172.17.0.2:46041->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.518393 packetgen.go:65: Error sending packet: lookup rg.ru on 24.200.210.241:53: read udp 172.17.0.2:46041->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.520251 utils.go:153: Error looking up DNS: lookup interfax.ru on 24.200.210.241:53: read udp 172.17.0.2:47646->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.520278 packetgen.go:65: Error sending packet: lookup interfax.ru on 24.200.210.241:53: read udp 172.17.0.2:47646->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.520265 utils.go:153: Error looking up DNS: lookup interfax.ru on 24.200.210.241:53: read udp 172.17.0.2:47646->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.520301 packetgen.go:65: Error sending packet: lookup interfax.ru on 24.200.210.241:53: read udp 172.17.0.2:47646->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521631 utils.go:153: Error looking up DNS: lookup lenta.ru on 24.200.210.241:53: read udp 172.17.0.2:34577->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521653 packetgen.go:65: Error sending packet: lookup lenta.ru on 24.200.210.241:53: read udp 172.17.0.2:34577->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521654 utils.go:153: Error looking up DNS: lookup ria.ru on 24.200.210.241:53: read udp 172.17.0.2:46580->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521666 utils.go:153: Error looking up DNS: lookup lenta.ru on 24.200.210.241:53: read udp 172.17.0.2:34577->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521707 packetgen.go:65: Error sending packet: lookup lenta.ru on 24.200.210.241:53: read udp 172.17.0.2:34577->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521688 packetgen.go:65: Error sending packet: lookup ria.ru on 24.200.210.241:53: read udp 172.17.0.2:46580->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521664 utils.go:153: Error looking up DNS: lookup ria.ru on 24.200.210.241:53: read udp 172.17.0.2:46580->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521778 packetgen.go:65: Error sending packet: lookup ria.ru on 24.200.210.241:53: read udp 172.17.0.2:46580->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521690 utils.go:153: Error looking up DNS: lookup roscosmos.ru on 24.200.210.241:53: read udp 172.17.0.2:54683->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521806 packetgen.go:65: Error sending packet: lookup roscosmos.ru on 24.200.210.241:53: read udp 172.17.0.2:54683->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521695 utils.go:153: Error looking up DNS: lookup roscosmos.ru on 24.200.210.241:53: read udp 172.17.0.2:54683->24.200.210.241:53: i/o timeout
2022/03/08 23:13:57.521831 packetgen.go:65: Error sending packet: lookup roscosmos.ru on 24.200.210.241:53: read udp 172.17.0.2:54683->24.200.210.241:53: i/o timeout

**Comment by Arriven** [comment]
Both this and #247 seem to indicate that there are a lot of network problems on the instance you are running this app on. Can you check out if anything else is working?
