### ISSUE TITLE
Error building raw connection: listen ip4:tcp 0.0.0.0

### ISSUE THREAD

**Issue by Aljnk** [arriven/db1000n#265]
Starts from v.0.6 my log looks like this

**2022/03/09 14:36:00.109907 packetgen.go:66: Error building raw connection: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/09 14:36:00.110213 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.**
2022/03/09 14:36:00.109907 packetgen.go:66: Error building raw connection: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/09 14:36:00.111680 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/09 14:36:00.109907 packetgen.go:66: Error building raw connection: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/09 14:36:00.115878 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/09 14:36:00.109907 packetgen.go:66: Error building raw connection: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/09 14:36:00.116818 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: socket: An attempt was made to access a socket in a way forbidden by its access permissions.
2022/03/09 14:36:00.165211 countrychecker.go:55: Current country: Saudi Arabia
2022/03/09 14:36:59.965111 runner.go:161: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/09 14:36:59.965658 runner.go:162: Attack is successful! Russian warship, go fuck yourself!
2022/03/09 14:36:59.967455 runner.go:163: The app has generated approximately 332476 bytes of traffic
**2022/03/09 14:37:00.045466 config.go:35: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json"
2022/03/09 14:37:00.045466 config.go:88: The config has not changed. Keep calm and carry on!**
2022/03/09 14:37:59.746600 runner.go:161: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/09 14:37:59.748345 runner.go:162: Attack is successful! Russian warship, go fuck yourself!
2022/03/09 14:37:59.755865 runner.go:163: The app has generated approximately 672564 bytes of traffic
**2022/03/09 14:37:59.848304 config.go:35: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json"
2022/03/09 14:37:59.848304 config.go:88: The config has not changed. Keep calm and carry on!**
2022/03/09 14:38:59.747361 runner.go:161: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/09 14:38:59.747361 runner.go:162: Attack is successful! Russian warship, go fuck yourself!
2022/03/09 14:38:59.748118 runner.go:163: The app has generated approximately 1017832 bytes of traffic
**2022/03/09 14:38:59.821323 config.go:35: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json"
2022/03/09 14:38:59.821323 config.go:88: The config has not changed. Keep calm and carry on!**
2022/03/09 14:39:59.756180 runner.go:161: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/09 14:39:59.756778 runner.go:162: Attack is successful! Russian warship, go fuck yourself!
2022/03/09 14:39:59.758125 runner.go:163: The app has generated approximately 1340392 bytes of traffic
**2022/03/09 14:39:59.835591 config.go:35: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json"
2022/03/09 14:39:59.835591 config.go:88: The config has not changed. Keep calm and carry on!**
2022/03/09 14:40:59.742627 runner.go:161: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/09 14:40:59.742627 runner.go:162: Attack is successful! Russian warship, go fuck yourself!
2022/03/09 14:40:59.744731 runner.go:163: The app has generated approximately 1673592 bytes of traffic
**2022/03/09 14:40:59.818213 config.go:35: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json"
2022/03/09 14:40:59.818213 config.go:88: The config has not changed. Keep calm and carry on!**

**Comment by Aljnk** [comment]
Thanks

**Comment by SLDay** [comment]
Dear Arriven, could you please advise how can I solve similar problem. I receive following errors when I run the tool in Windows 10 with Administrator previlages.

```2022/03/09 17:17:49.486864 packetgen.go:66: Error building raw connection: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.
2022/03/09 17:17:49.498791 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.```
