### ISSUE TITLE
error running job: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied

### ISSUE THREAD

**Issue by pashagolub** [arriven/db1000n#269]
```shell
PS> go version
go version go1.17.6 windows/amd64

PS> git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

PS> git log --pretty=format:'%h' -n 1
9b6ad5e
```
--

```
..
2022/03/09 17:29:32.543983 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.
2022/03/09 17:29:32.551535 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.
2022/03/09 17:29:32.550650 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.
2022/03/09 17:29:32.552248 runner.go:112: error running job: listen ip4:tcp 0.0.0.0: bind: An invalid argument was supplied.
...
```

**Comment by Arriven** [comment]
unless you run it with sudo this is kinda to be expected, see packetgen reference [here](https://github.com/Arriven/db1000n/blob/main/docs/configuration.md)
you should be able to see in the logs how many jobs were started overall to be able to assess how much impact these errors have on the overall effectiveness of the program. The only thing I could do here is improve logging to better indicate that this is kinda expected but there are couple of factors currently that make me shift focus towards other features (if I manage to do them it'll be huge)

**Comment by pashagolub** [comment]
terminal is running under admin role

**Comment by Arriven** [comment]
apparently, this feature is not supported in windows itself, see relevant issue for the go runtime https://github.com/golang/go/issues/6786
