### ISSUE TITLE
OOM killed

### ISSUE THREAD

**Issue by synapse-unix** [Arriven/db1000n#272]
Got container **OOMkilled** today, from syslog:
> Mar  9 18:14:14 http-service-0 kernel: [295692.212091] [  50111]     0 50111   224138    49259   520192        0             0 main
> Mar  9 18:14:14 http-service-0 kernel: [295692.212094] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=d1dfb06deee8498945c4fa337c6ec6d8336755e2f7be147ec3ec9190bfe224cc,mems_allowed=0,global_oom,task_memcg=/docker/d1dfb06deee8498945c4fa337c6ec6d8336755e2f7be147ec3ec9190bfe224cc,task=main,pid=50111,uid=0
> Mar  9 18:14:14 http-service-0 kernel: [295692.212175] Out of memory: Killed process 50111 (main) total-vm:896552kB, anon-rss:197036kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:508kB oom_score_adj:0
> Mar  9 18:14:14 http-service-0 kernel: [295692.232310] oom_reaper: reaped process 50111 (main), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
> Mar  9 18:14:23 http-service-0 dockerd[2849]: time="2022-03-09T18:14:23.365569730Z" level=info msg="ignoring event" container=d1dfb06deee8498945c4fa337c6ec6d8336755e2f7be147ec3ec9190bfe224cc module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"

Checking `docker stats` now. Advice what information should be collected?

Running currently with `sudo docker run -it -d --pull always --restart on-failure ghcr.io/arriven/db1000n`

**Comment by nonchalant-enthusiast** [comment]
Assuming you're on the latest build, it's probably related to the low RAM, it's recommended to have at least 2GB. See #54

**Comment by Arriven** [comment]
First of all I'd check for used version, the system you are running it on, how much memory is available to docker. If those seem plausible we can start digging deeper

**Comment by synapse-unix** [comment]
It’s Azure’s Standard_D2s_v3 instance, 2 core CPU, 8Gb RAM. 1 container was running, Load average is about 2.0.

I just checked stats of the running for 10h containers, RAM usage is around 161Mb. So it is good.

How now image version updates in a running container? Can it be caused that src in the container was incompatible with a newly fetched target config that caused a sudden spike that result in OOM?
