### ISSUE TITLE
Support of system variable like ALL_PROXY with schemes http://ip:port and socks5://ip:port for using with tor and packetgen job type

### ISSUE THREAD

**Issue by lollypot** [Arriven/db1000n#279]
Continue of https://github.com/Arriven/db1000n/pull/207

For now we can set http proxy in two variants:

1. By system variable like `HTTP_PROXY` or `http_proxy`
2. By app argument like `-proxy 172.17.0.1:8080`

Both variants are work very well. But it seems we have other types of jobs which require socks5 proxy, especially packetgenJob. As I see in go library we can use something like this https://cs.opensource.google/go/x/net/+/27dd8689:proxy/proxy.go;l=40 and https://cs.opensource.google/go/x/net/+/27dd8689:proxy/proxy.go;l=92 and set it like `docker run -e HTTP_PROXY=http://172.17.0.1:8080 -e ALL_PROXY=soks5://172.17.0.1:9150` I have tried to set it(`ALL_PROXY`) but it not work for packetgen. Can you say me how I can implement this dealer for this job or just add support of ALL_PROXY system variable with schemes? I am not so experienced with go-lang yet.
All of this need to run a bunch db1000n applications in k8s cluster with tor http and socks proxy. Take a look here https://github.com/lollypot/k8s-runners/tree/master/helm for examples.

Thank you.

**Comment by Arriven** [comment]
that's actually a good question. I'd be looking at something like https://pkg.go.dev/golang.org/x/net/proxy#SOCKS5 
I'm not sure whether it would be easier to embed it into packetgen or rawnet jobs but both of them use standard go net package to send their data so it should be possible. Will take a look at it myself a bit later

**Comment by Arriven** [comment]
@lollypot considering the fact that socks5 proxies don't work for udp I feel like it would also be impossible to add them to packetgen but feel free to experiment

**Comment by Arriven** [comment]
Closing this as most proxies don't support udp or raw ip traffic (including tor)
