### ISSUE TITLE
What's the status on "Slow Loris" method?

### ISSUE THREAD

**Issue by SomalianCoolhacker** [Arriven/db1000n#281]
Hi, when looking through changes in the main branch, I've discovered that, quote,

> `Warning`: slow-loris from `testconfig.json` is not yet finished and may overload the app due to not handling config refreshes

But the `slowloris.go` script is being updated frequently, so I'm wondering if it has already been fixed and does the provided example in `testconfig.json` can be used from now on to test attacks?

Many thanks to all contributors.

**Comment by Arriven** [comment]
ah, right, forgot to remove that note, thanks for bringing it up!
