### ISSUE TITLE
IP address spoofing

### ISSUE THREAD

**Issue by bmirnoff** [Arriven/db1000n#292]
I observed code and see that config allows templating for headers and requests. But what about to add default IP address spoofing solution that adds headers for each HTTP attack 

https://github.com/MHProDev/MHDDoS/blob/main/start.py#L566
`
("X-Forwarded-Proto: Http\"
                f"X-Forwarded-Host: {self._target.raw_host}, 1.1.1.1"
                f"Via: {spoof}"
                f"Client-IP: {spoof}"
                f'X-Forwarded-For: {spoof}'
                f'Real-IP: {spoof}'
)

`

**Comment by sivillakonski** [comment]
@bmirnoff, The problem here is that `X-Forwarded-*` headers are usually set by the load balancers. I can't be 100% confident, but it feels like these headers would be overwritten by the reverse proxy servers on the target side
