### ISSUE TITLE
Broken download links in README file

### ISSUE THREAD

**Issue by artempolikarpov** [Arriven/db1000n#310]
Unable to download due to broken tags in links (section Download an application for your platform)
> [Windows]([https://github.com/Arriven/db1000n/releases/download/{{](https://github.com/Arriven/db1000n/releases/download/%7B%7B) git_latest_version_tag }}/db1000n-{{ git_latest_version_tag }}-windows-386.zip)
> [Mac M1]([https://github.com/Arriven/db1000n/releases/download/{{](https://github.com/Arriven/db1000n/releases/download/%7B%7B) git_latest_version_tag }}/db1000n-{{ git_latest_version_tag }}-darwin-arm64.tar.gz)
> ...

**Comment by Arriven** [comment]
Fixed, forgot to update readme properly after switching to mkdocs. please use https://arriven.github.io/db1000n for all the docs related to this package
