### ISSUE TITLE
db1000n does not work (error screen inside)

### ISSUE THREAD

**Issue by koupok** [Arriven/db1000n#311]
![ошибка ддос](https://user-images.githubusercontent.com/101471698/158027620-b113866f-cafc-4366-8677-b86505f3e188.JPG)
![ошибка 1000db](https://user-images.githubusercontent.com/101471698/158027693-6eb7f7fa-638e-416e-9f50-fa02061034ac.JPG)

**the network and internet are fine**

**Comment by Samvolian** [comment]
+1

**Comment by Arriven** [comment]
It's only one of the jobs that doesn't work. See https://github.com/Arriven/db1000n/issues/269
