### ISSUE TITLE
v0.7.0 says  DB1000n [Version: v0.0.1]

### ISSUE THREAD

**Issue by su-hs** [Arriven/db1000n#322]
I assume it's left over hardcoded version value or somewhere the code has not been changed properly

<img width="570" alt="Screenshot 2022-03-13 at 13 14 20" src="https://user-images.githubusercontent.com/100500001/158058905-acebb531-962b-4985-a289-63b785ee7fb3.png">

Reproduced via executables on MacOS
- for Intel CPU https://github.com/Arriven/db1000n/releases/download/v0.7.0/db1000n-v0.7.0-darwin-amd64.tar.gz
- for M1 CPU https://github.com/Arriven/db1000n/releases/download/v0.7.0/db1000n-v0.7.0-darwin-arm64.tar.gz

cc/ @Arriven ; @bitshape

**Comment by arfgdev** [comment]
it seems that makefile does not add `ldflags` `+ go build -o build-artifacts-1647175086/db1000n ''` (https://github.com/Arriven/db1000n/runs/5527622054?check_suite_focus=true line 185 )

**Comment by Arriven** [comment]
Had some troubles setting up the release action to work with makefile (forgot that make is running on ubuntu for all targets, just uses different GOOS variable). Should be fixed in v0.7.4

**Comment by su-hs** [comment]
I do confirm - FIXED in `v0.7.4`.

**Comment by su-hs** [comment]
@Arriven hope u will get notif from closed issue, but, look,

```
docker run --pull always ghcr.io/arriven/db1000n:latest
```

=>


![image](https://user-images.githubusercontent.com/100500001/158080747-98fee9bb-e5ba-43f8-9695-a198fbf964db.png)

`sha256:06b9ddf9b3228317b7cef1020bce96364a9a7b46c74d3ce3973e1b5c1daa68a8`


that image seems to be old. How it works? When new release appear, do you also re-publish image to Docker registry?

**Comment by su-hs** [comment]
@Arriven I do confirm, that latest `v0.7.5` is ALSO OK in regards to described issue:


```
$ docker run --rm -it --pull always **ghcr.io/arriven/db1000n:latest**

latest: Pulling from arriven/db1000n
8fa90b21c985: Pull complete 
26195c2debd0: Pull complete 
233111e583bf: Pull complete 
222ac4e0a4cc: Pull complete 
Digest: sha256:b28d78d03e3bc4cb6045f3d109003796d511c00ffaab03fb5c6f743af582f625
Status: Downloaded newer image for ghcr.io/arriven/db1000n:latest

2022/03/14 16:43:58.340968 main.go:54: DB1000n **[Version: v0.7.5]**[PID=1]
```
