### ISSUE TITLE
Not sure this is an issue: Received HTTP 304 not modified..version 0.7.4

### ISSUE THREAD

**Issue by SamvSeer** [Arriven/db1000n#327]
error message while running: Received HTTP 304 not modified..version 0.7.4...darwin arm64

<img width="535" alt="Schermafbeelding 2022-03-13 om 16 59 07" src="https://user-images.githubusercontent.com/25307892/158068473-8625f693-ec4a-40af-b5eb-0075ae9d155a.png">

**Comment by arfgdev** [comment]
could you describe the way to reproduce it?

**Comment by ChangeMe83** [comment]
The same issue
`2022/03/13 19:44:51.195001 config.go:103: Received HTTP 304 Not Modified
2022/03/13 19:44:51.195023 config.go:59: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/13 19:44:51.195059 config.go:143: The config has not changed. Keep calm and carry on!
2022/03/13 19:45:51.156377 runner.go:152: Атака проводиться успішно! Руський воєнний корабль іди нахуй!
2022/03/13 19:45:51.157563 runner.go:153: Attack is successful! Russian warship, go fuck yourself!
2022/03/13 19:45:51.157583 runner.go:154: The app has generated approximately 1458987852 bytes of traffic
2022/03/13 19:45:51.157586 runner.go:157: Of which for 2823430 bytes we received some response from the target
`

**Comment by arfgdev** [comment]
it is not an error. 
it is an expected behavior https://github.com/Arriven/db1000n/blob/v0.7.4/src/runner/config/config.go#L103

**Comment by SamvSeer** [comment]
ok..will close it. Just reported it because this message was not there in earlier versions.
