### ISSUE TITLE
User question: not clear wich version to use

### ISSUE THREAD

**Issue by crocangIt** [Arriven/db1000n#335]
Hi,
It is not clear which db1000n (Windows) version is advised to use. Are you still testing V7+ ? ( v6 and v7 are using different config files).

It would be better to hide  countrychecker messages in v0.7.5:"Can't check users country.** Please manually check that VPN is enabled or that you have non Ukrainian IP address."
See in v0.7.5 :
2022/03/14 17:31:44.499782 main.go:54: DB1000n [Version: v0.7.5][PID=1188]
2022/03/14 17:31:44.500358 countrychecker.go:28: Checking IP address, attempt #0
2022/03/14 17:31:48.528093 **countrychecker.go:44: Can't check users country.** Please manually check that VPN is enabled or that you have non Ukrainian IP address.
2022/03/14 17:31:48.528413 countrychecker.go:28: Checking IP address, attempt #1
....
2022/03/14 17:31:58.722509 countrychecker.go:97: Current country: Costa Rica (143.202.160.2)
2022/03/14 17:32:00.060089 config.go:60: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/14 17:32:00.060089 config.go:151: New config received, applying

Greetings, Ivo

**Comment by crocangIt** [comment]
![image](https://user-images.githubusercontent.com/101589346/158242117-e72bcedc-154d-49db-8dc1-83faf7e7ee23.png)
Google drive doc- under Windows is old version. I know how to get the latest one. But we shouldn't confuse potential helpers.

**Comment by justsomeguy0** [comment]
Latest v0.7.6 is not working for me at all (though my windows firewall prompt appeared and I allowed what it asked), previous one (v.0.7.5) works.

**Comment by iamtodor** [comment]
@crocangIt g-doc is not up to date. it's not supported a long time ago. please read the official documentation
- https://arriven.github.io/db1000n/en/#for-dummies
- https://arriven.github.io/db1000n/uk/#%D0%B4%D0%BB%D1%8F-%D0%BD%D0%BE%D0%B2%D0%B0%D1%87%D0%BA%D1%96%D0%B2

**Comment by AnatolHol** [comment]
Versions 0.7.6 and 0.7.7 do not work under win10 21H2 (19044.1586), or am I doing something wrong
![Буфер обмена](https://user-images.githubusercontent.com/101464704/158259123-fd6bd9b0-a0d4-4458-a961-dc6cb64e8af4.png)
?

**Comment by crocangIt** [comment]
> Versions 0.7.6 and 0.7.7 do not work under win10 21H2 (19044.1586), or am I doing something wrong ![Буфер обмена](https://user-images.githubusercontent.com/101464704/158259123-fd6bd9b0-a0d4-4458-a961-dc6cb64e8af4.png) ?

Same issue here. I went back to last working-  v0.7.5

**Comment by Arriven** [comment]
@AnatolHol @crocangIt there was a bug in v0.7.6, should be fixed in v0.7.8 (see #339 )
