### ISSUE TITLE
Feature request: "-use-advanced-config" flag for binary distribution

### ISSUE THREAD

**Issue by dmitry-salnikov** [Arriven/db1000n#341]
Since you've added self-update for binary distribution - thanks! - could you please add the CLI option to use advanced config - same as used by docker image `ghcr.io/arriven/db1000n-advanced` mentioned in the docs.

It's preferrable to add kind of `-use-advanced-config` flag instead of specifying exact config path, because when running the tool like
```sh
./db1000n -enable-self-update -с https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.adv.json
```
the binary eventually updates to 0.8, and config version 0.7 may become incompatible.

So, it would be awesome to be able to run the binary as:

```
./db1000n -enable-self-update -use-advanced-config
```

**Comment by sivillakonski** [comment]
Hi folks, thank you for your feedback!
Lemme see what we can do with this :)
