### ISSUE TITLE
On AWS Windows t3.small

### ISSUE THREAD

**Issue by S767** [Arriven/db1000n#344]
Windows executable get error:

C:\Users\Administrator\Desktop>db1000n.exe
2022/03/15 07:47:17.100981 main.go:54: DB1000n [Version: v0.7.7][PID=3964]
2022/03/15 07:47:17.101527 countrychecker.go:28: Checking IP address, attempt #0
2022/03/15 07:47:18.806696 countrychecker.go:97: Current country: Germany (212.115.110.190)
2022/03/15 07:47:18.807715 prometheus.go:213: Can't get system cert pool
2022/03/15 07:47:19.534304 config.go:60: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x10 pc=0x12a76b0]

goroutine 40 [running]:
crypto/x509.(*CertPool).addCertFunc(...)
        /usr/local/go/src/crypto/x509/cert_pool.go:188
crypto/x509.(*CertPool).AppendCertsFromPEM(0x0, {0x128e5000, 0x31e, 0x400})
        /usr/local/go/src/crypto/x509/cert_pool.go:226 +0x280
github.com/Arriven/db1000n/src/utils/metrics.getTLSConfig()
        /github/workspace/src/utils/metrics/prometheus.go:227 +0xeb
github.com/Arriven/db1000n/src/utils/metrics.pushMetrics({0x19d79bc, 0x1284bef0}, {0x128a69a8, 0x3, 0x3})
        /github/workspace/src/utils/metrics/prometheus.go:244 +0xe4
created by github.com/Arriven/db1000n/src/utils/metrics.ExportPrometheusMetrics
        /github/workspace/src/utils/metrics/prometheus.go:173 +0x14a

**Comment by Arriven** [comment]
should be fixed in v0.7.8 (see #339 )
