### ISSUE TITLE
Version 0.7.9 crashing on Windows10: need to fix

### ISSUE THREAD

**Issue by crocangIt** [Arriven/db1000n#347]
v0.7.8 is working, but v0.7.9:

C:\Users\Ivo\Desktop\db1000n-v0.7.9-windows-386>db1000n.exe
2022/03/15 12:40:03.255152 main.go:55: DB1000n [Version: v0.7.9][PID=4732]
2022/03/15 12:40:03.255152 countrychecker.go:28: Checking IP address, attempt #0
2022/03/15 12:40:06.134636 countrychecker.go:97: Current country: Netherlands (77.249.234.246)
2022/03/15 12:40:06.135413 prometheus.go:247: Can't get tls config
2022/03/15 12:40:06.186500 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/15 12:40:06.186500 config.go:125: New config received, applying
2022/03/15 12:40:06.188701 http.go:147: Attacking http://94.180.145.12:1050
.............
2022/03/15 12:41:23.742202 http.go:147: Attacking https://gos.etpgpb.ru/
2022/03/15 12:41:23.715137 http.go:147: Attacking https://etp.gpb.ru/
**runtime: out of memory: cannot allocate 268435456-byte block (1081573376 in use)
fatal error: out of memory**

goroutine 709 [running]:
runtime.throw({0x16cf71b, 0xd})
        /usr/local/go/src/runtime/panic.go:1198 +0x64 fp=0x239cfc54 sp=0x239cfc40 pc=0xf68f54
runtime.(*mcache).allocLarge(0x2930528, 0x10000000, 0x0, 0x1)
        /usr/local/go/src/runtime/mcache.go:229 +0x250 fp=0x239cfc88 sp=0x239cfc54 pc=0xf44ca0
runtime.mallocgc(0x10000000, 0x1607c40, 0x1)
        /usr/local/go/src/runtime/malloc.go:1088 +0x48b fp=0x239cfcd8 sp=0x239cfc88 pc=0xf3bd1b
runtime.makeslice(0x1607c40, 0x4000000, 0x4000000)
        /usr/local/go/src/runtime/slice.go:98 +0x4f fp=0x239cfcec sp=0x239cfcd8 pc=0xf7e1df
golang.org/x/crypto/scrypt.Key({0x131f4b10, 0x2c, 0x30}, {0x131cab00, 0x2c, 0x40}, 0x40000, 0x8, 0x1, 0x20)
        /go/pkg/mod/golang.org/x/crypto@v0.0.0-20220214200702-86341886e292/scrypt/scrypt.go:204 +0x113 fp=0x239cfd4c sp=0x239cfcec pc=0x122f333
filippo.io/age.(*ScryptIdentity).unwrap(0x131ee9e0, 0x1329b920)
        /go/pkg/mod/filippo.io/age@v1.0.0/scrypt.go:159 +0x311 fp=0x239cfdc0 sp=0x239cfd4c pc=0x1233331
.......
goroutine 1380 [runnable]:
text/template/parse.(*lexer).run(0x13426940)
        /usr/local/go/src/text/template/parse/lex.go:228
created by text/template/parse.lex
        /usr/local/go/src/text/template/parse/lex.go:223 +0x192

**Comment by Arriven** [comment]
OOM errors again, it seems like even with the latest change to encrypt only part of the config it still doesn't have enough memory to parse it. You can temporarily get around it by passing `--skip-encrypted` via commandline args

on a bit different topic, @crocangIt does the app crash completely or does it print this error and continues generating at least some traffic?

**Comment by crocangIt** [comment]
> 
It seems that some traffic is generated.
It is busy for a few seconds and then it crashes completely:
See the attachment.


[log.txt](https://github.com/Arriven/db1000n/files/8253607/log.txt)

**Comment by AnatolHol** [comment]
> @crocangIt are you by any chance using a machine with somewhere around 1 GB of RAM or are there more resources? want to confirm a suspicion

I have 24 GB RAM, Win10 x64, same problems.

**Comment by kurlyk-dev** [comment]
Crashing on AWS `t3.small` instances too.

**Comment by Arriven** [comment]
@crocangIt not removed, just "optimized": we discovered that when multiple threads try to decrypt the data in parallel - each of them have to create their own decryption key copy and each copy takes roughly 256Mb of RAM. I've changed the config to only contain one encrypted part but I'm also working on making it so that no two threads can decrypt data in parallel (it's not crucial to performance as decryption is done only once when config changes but will eliminate this issue completely)
