### ISSUE TITLE
prometheus.go:273: Can't push metrics to gateway, trying to change gateway...?

### ISSUE THREAD

**Issue by SamvSeer** [Arriven/db1000n#348]
output while running job db1000n:

prometheus.go:273: Can't push metrics to gateway, trying to change gateway

**Comment by Arriven** [comment]
we've enabled metrics to be able to see how much traffic we generate and be able to adapt our strategy accordingly. this message just means that we can't see the traffic you generate (so we're slightly underestimate the overall traffic but it's not critical as we should still see the general picture and tendencies)

Most likely causes are:

1. the app can't connect to the gateway - this could either mean that our metrics infrastructure is temporary down or that the location that you are running the app from can't connect to the servers (i.e. if you're running it from within a vpn into russia and they've blocked the ip ranges we use for metrics you'll get this message, you can try querying some regular websites via curl to have more info about general network availability of your node)
1.  you're using beta version or build your exe from scratch and don't have the encryption key used to protect our metrics infrastructure (it's built into the official binaries and docker image though) - this is less likely as you would get a different error AFAIR

again, this is not critical and you are still generating traffic and contributing to the cause - we just see a smaller number in our dashboard (we weren't seeing anything at all prior to yesterday anyway :) )

**Comment by SamvSeer** [comment]
thanks for the feedback. will close the issue..btw running the job with VPN..currently from France.....same message occurs
