### ISSUE TITLE
DB1000N not working on Windows

### ISSUE THREAD

**Issue by ciegoo** [Arriven/db1000n#362]
Hi friends, 

I am using your windows script file in different computers in order to attack as much as possible. I have tried some versions but only works good 5.12. This is the version that allows to send about 60 gB attack per day, other newer version doesn't work or send 2,4 gB per day. I am not an axpert in this staff but something is failing here. If I am wrong please explain to me what version do I have to use. Thanks in advance

**Comment by Lagovas** [comment]
which versions did you try? 0.5.12 released 12 days ago and changed a lot since that time and has a lot of fixes. maybe you will try some fresh versions?)

**Comment by udjfvnsaoepna** [comment]
Download last version
https://github.com/Arriven/db1000n/releases

**Comment by ciegoo** [comment]
Hi,

Fresh versions don't generate the same traffic weight than 5.12 does. Some
new versions crashed, ut now with last update is working fine.

Thanks,

Regards

**Comment by Arriven** [comment]
@ciegoo are you actively comparing 5.12 with latest version or those numbers are historical values?

**Comment by ciegoo** [comment]
Hi,
Some version newer than 5.12 had problem working in Windows, but now release 7.12 works good. Thanks for your comments.

**Comment by ciegoo** [comment]
Thanks,

Last version is working.

Regards


Un saludo,

Diego
