### ISSUE TITLE
Packetgen job write ip 0.0.0.0->xxx.xxx.xxx.xxx: sendmsg: invalid argument error

### ISSUE THREAD

**Issue by temorfeouz** [Arriven/db1000n#363]
Hi! Trying build custom config file, tcp and udp jobs working great, make more traffic than mhddos)
But ive faced with next error now:
{"level":"error","ts":1647453131.335018,"caller":"runner/runner.go:133","msg":"error running job","error":"write ip 0.0.0.0->xxx.xxx.xxx.xxx sendmsg: invalid argument","stacktrace":"github.com/Arriven/db1000n/src/runner.(*Runner).runJobs.func1\n\github.com/Arriven/db1000n/src/runner/runner.go:133"}
Bin version:  [Version: v0.7.11]
OS: osx
config:
{
  "jobs": [
    {
      "type": "packetgen",
      "args": { 
        "host": "xxx.xxx.xxx.xxx",
        "port": "XX",
        "packet": {
          "payload": "test:blah",
          "ethernet": {
            "src_mac": "{{ random_mac_addr }}",
            "dst_mac": "{{ random_mac_addr }}"
          },
          "ip": {
            "src_ip": "{{ local_ip }}",
            "dst_ip": "xxx.xxx.xxx.xxx"
          },
          "tcp": {
            "src_port": "{{ random_port }}",
            "dst_port": "XX",
            "flags": {
              "syn": true
            }
          },
          "udp": {
            "src_port": "{{ random_port }}",
            "dst_port": "XX"
          }
        }
      }
    }
  ]
}

maybe something wrong with config(i try build config file using test config in repository)?

**Comment by Arriven** [comment]
Oh, btw, current implementation doesn't support specifying both tcp and udp payload in the same job at once and udp one prevails, you can try disabling udp payload there to see if it works

**Comment by temorfeouz** [comment]
i run as sudo, ive tryed remove udp option right now but it nothing changed. I saw you inspired by https://github.com/bilalcaliskan/syn-flood
i going to check how this project will do this

**Comment by temorfeouz** [comment]
i`ve found out problem right now) problem in osx, when i run in docker all working good.
here example of working config 
 {
      "type": "packetgen",
      "args": { 
        "host": "XX",
        "port": "XX",
        "packet": {
          "payload": "test:blah",
          "ethernet": {
            "src_mac": "{{ random_mac_addr }}",
            "dst_mac": "{{ random_mac_addr }}"
          },
          "ip": {
            "src_ip": "{{ local_ip }}",
            "dst_ip": "XX"
          },
          "tcp": {
            "src_port": "{{ random_port }}",
            "dst_port": "XX",
            "flags": {
              "syn": true
            }
          }
        }
      }
    }
