### ISSUE TITLE
Built-in DDoS protection bypass

### ISSUE THREAD

**Issue by localdotcom** [Arriven/db1000n#376]
Hi guys, does db1000n have built-in options to bypass DDoS protections like DDoS Guard, Cloudflare DDoS protection etc.?

**Comment by Arriven** [comment]
It's not built in but it is already configurable enough to bypass some ddos-guard configurations and I'm working on functionality that would allow bypassing cloudflare and similar services

**Comment by Arriven** [comment]
CLosing this in favor of #293
