### ISSUE TITLE
please add to the guide that for some locations in aws config main instance type need to be changed from t2.micro to t3.micro

### ISSUE THREAD

**Issue by DTBLA** [Arriven/db1000n#377]
<img width="355" alt="image" src="https://user-images.githubusercontent.com/36825912/159132664-6d0c5a0d-b214-4834-a394-fa5be0fbe939.png">

**Comment by Arriven** [comment]
Probably would be best if you go ahead and make a PR yourself since as I understand it's not all regions that need this

**Comment by alexdanger** [comment]
i suggest to add also graviton instances, as they have lowest prices and better cpu/mem throughput.

**Comment by Amet13** [comment]
I believe it's already covered by https://github.com/Arriven/db1000n/pull/403/files#diff-e0beaf635e7e58ca4243047eed9acca64a5426826fb4c19579c3fef5c6cc6cc2R22
