### ISSUE TITLE
Prometheus charts

### ISSUE THREAD

**Issue by dzhonzojdberg** [Arriven/db1000n#379]
Please make guest access to Prometheus charts.

**Comment by Lagovas** [comment]
for what you need it? 
looking on such random nickname It looks strange. Personally, I prefer to close such issues from bots with strange requests)

**Comment by dzhonzojdberg** [comment]
> for what you need it? looking on such random nickname It looks strange. Personally, I prefer to close such issues from bots with strange requests)

Hi, not a bot, a real person, actively using your program, by the way, thank you for it, it is a great job for good, I realized that it connects to Prometheus servers, there is no possibility to deploy your own, and not enough knowledge, but I would like to see the general statistics, graphics, success or failure, it will give a more correct understanding of its work, as well as the motivation to use it in the future. (sorry for my english)

**Comment by Arriven** [comment]
@dzhonzojdberg you can use Prometheus endpoint if you use unencrypted build (i.e. you build the app from source) it's available at ":9090/metrics" when `--prometheus_on` is set to true (it's set to true by default)

**Comment by dzhonzojdberg** [comment]
@Arriven Thanks! That what I needed!)
