### ISSUE TITLE
Load amount configuration

### ISSUE THREAD

**Issue by mErlin-sp** [Arriven/db1000n#382]
Hello. I`ve looking into your project and it seems pretty good but i need to run up to 10 docker containers to utilize full of my cpu. Do we have a possibility to configurate amount of load (threads count, for example) in this software?

**Comment by Arriven** [comment]
you can use `--scale 10` to achieve that same result

**Comment by Arriven** [comment]
no automatic cpu load detection for now (probably wouldn't be as good anyway since a lot of use cases are limited by network performance or amount of unique IP addresses you can get)
