### ISSUE TITLE
ver 0.7.12 & ver.0.8.0

### ISSUE THREAD

**Issue by S767** [Arriven/db1000n#386]
Зі вчора генерує мало трафіку (через windows аплікейшн на AWS + ClearVPN) та сьогодні
видає на версії 8
2022/03/21 10:58:47.659348 config.go:125: New config received, applying
2022/03/21 10:58:47.661349 runner.go:145: 14 job instances (re)started
[Error] No traffic generated. If you see this message a lot - contact admins
2022/03/21 10:59:47.420024 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/21 10:59:47.420390 runner.go:81: The config has not changed. Keep calm and carry on!

**Comment by udjfvnsaoepna** [comment]
Я понял в чем, проблема. В конфиге только TCP задание.
https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json

**Comment by Arriven** [comment]
latest config is this one: https://t.me/itarmyofukraine2022/222
soon will be updated with this https://t.me/itarmyofukraine2022/223

**Comment by MetaMmodern** [comment]
@udjfvnsaoepna  But why having only tcp's does not generate traffic?

**Comment by Arriven** [comment]
Closing this as #12 was already fixed
