### ISSUE TITLE
Something weird is going on, contact admins

### ISSUE THREAD

**Issue by MetaMmodern** [arriven/db1000n#387]
![image](https://user-images.githubusercontent.com/42899786/159252632-cd9ca524-85d6-4529-ad5f-6005fca1466f.png)
Started db1000n using tmux:

`tmux new -d "db1000n -enable-self-update"`

@Arriven What's wrong here? Worked fine until 10AM or so

**Comment by Arriven** [comment]
the config has changed to include only tcp targets, see #386
