### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by human1ty** [Arriven/db1000n#389]
Is it possible to feed the proxy list either via a direct link or a local text file as an argument to a tool
The intention is to apply a randomly selected proxy during the attack
As a proposal - do a test for some N number of proxies in order to
1) Find out whether the proxy usable
2) Find out its location
3) Find out response - the quicker the better
4) Make a priority proxy list
5) Apply/rotate proxy based on a priority defined in 4)

A proxy list arg is a list of an anonymous proxy in the following format

XX.XX.XX.XX:PPPP
YY.YY.YY.YY:PPPP

XX.XX.XX.XX - address
PPPP - port

The intention
./db1000n -p <file_or_link>

ps. if it's already implemented - please point to a doc

**Comment by Arriven** [comment]
It's not implemented as a full blown feature but it's possible to achieve something of the following already by utilizing `--proxy` commandline flag. Accepts a comma separated list of proxies but actual jobs just take random entries from that list. The argument can be templated using go template engine similar to most parts of the remote config so you can hack it to update the list from time to time (see docs/advanced/configuration.md, might be a bit outdated)

**Comment by Arriven** [comment]
I'm not sure implementing full proxy rotation solution inside the app would be viable though, could be easier to setup a separate solution that would control proxies and just feed the list to db1000n
