### ISSUE TITLE
Failed to unmarshal job configs, will keep the current one: invalid character '}' looking for beginning of object key string

### ISSUE THREAD

**Issue by JeyM1** [Arriven/db1000n#401]
Full log:
```
2022/03/23 17:51:27.029769 main.go:58: DB1000n [Version: v0.7.12][PID=442416]
2022/03/23 17:51:27.030119 countrychecker.go:28: Checking IP address, attempt #0
2022/03/23 17:51:28.250122 countrychecker.go:97: Current country: Germany (138.68.81.60)
2022/03/23 17:51:28.349953 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/23 17:51:28.350099 config.go:125: New config received, applying
2022/03/23 17:51:28.350270 config.go:130: Failed to unmarshal job configs, will keep the current one: invalid character '}' looking for beginning of object key string
[Error] No traffic generated. If you see this message a lot - contact admins
2022/03/23 17:52:28.294674 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/23 17:52:28.294768 config.go:125: New config received, applying
2022/03/23 17:52:28.295062 config.go:130: Failed to unmarshal job configs, will keep the current one: invalid character '}' looking for beginning of object key string
[Error] No traffic generated. If you see this message a lot - contact admins
2022/03/23 17:53:28.292581 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/23 17:53:28.292684 config.go:125: New config received, applying
2022/03/23 17:53:28.292836 config.go:130: Failed to unmarshal job configs, will keep the current one: invalid character '}' looking for beginning of object key string
[Error] No traffic generated. If you see this message a lot - contact admins
2022/03/23 17:54:28.264664 config.go:40: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
2022/03/23 17:54:28.264832 config.go:125: New config received, applying
2022/03/23 17:54:28.265101 config.go:130: Failed to unmarshal job configs, will keep the current one: invalid character '}' looking for beginning of object key string
2022/03/23 17:54:47.807115 main.go:165: Terminating
```

Running on Ubuntu x86_64 (DigitalOcean droplet)

**Comment by DangelZM** [comment]
Same issue for

**Comment by ahalan** [comment]
Same on Apple silicon M1
> System Version: macOS 12.0.1 (21A559)
> Kernel Version: Darwin 21.1.0

**Comment by oholubovskyi** [comment]
Looks like its old version (v0.7.12).

Try the latest version https://github.com/Arriven/db1000n/releases/tag/v0.8.2

**Comment by asu-talk** [comment]
The issue reason is incorrect configuration json - redundant commas.
While the issue is not fixed by the channel administrators we can (as a workaround):
1. download configuration json manually (url is visible in the terminal)
2. open some online tool to verify json and save result locally
3. use -c command line argument to use sanitized configuration. For example:
   ./db1000n -c config/config.json

**Comment by oholubovskyi** [comment]
> The issue reason is incorrect configuration json - redundant commas. While the issue is not fixed by the channel administrators we can (as a workaround):
> 
> 1. download configuration json manually (url is visible in the terminal)
> 2. open some online tool to verify json and save result locally
> 3. use -c command line argument to use sanitized configuration. For example:
>    ./db1000n -c config/config.json

the latest version works without errors on Windows machine.

**Comment by asu-talk** [comment]
> > The issue reason is incorrect configuration json - redundant commas. While the issue is not fixed by the channel administrators we can (as a workaround):
> > 
> > 1. download configuration json manually (url is visible in the terminal)
> > 2. open some online tool to verify json and save result locally
> > 3. use -c command line argument to use sanitized configuration. For example:
> >    ./db1000n -c config/config.json
> 
> the latest version works without errors on Windows machine.

This issue is reproducible on linux.. but you are right - it is old version. Will check with new one. Thanks!

**Comment by JeyM1** [comment]
On newest version all is fine, thanks
