### ISSUE TITLE
Full CPU use, errors in the debug output

### ISSUE THREAD

**Issue by Luceoria** [Arriven/db1000n#408]
I've noticed 100% CPU usage - all cores are fully occupied.

using the -debug switch, following logs can be noticed:
 {"error": "dial tcp: lookup xx.xx.xx.xx : no such host"}
 {"error": "HostClient can't follow redirects to a different protocol, please use Client instead"}

Is this related to the newest config file?

**Comment by Luceoria** [comment]
[v0.8.1](https://github.com/Arriven/db1000n/releases/tag/v0.8.1) does not seem to have this issue.

**Comment by Arriven** [comment]
Errors are caused by a typo here https://github.com/db1000n-coordinators/LoadTestConfig/blob/main/config.v0.7.json#L177
(Extra space), will fix in couple of minutes but it only affects one of the targets. I'll try to see what's the cause of that CPU usage though

**Comment by Luceoria** [comment]
I might be mistaken here, but it looks like CPU resources are eaten by frequent DNS lookups for a non-existent host. Perhaps we should not query the DNS again if we already know the FQDN does not exit. Or at least implement a counter or time-based condition so DNS server is not hammered with hundreds of requests per second.

**Comment by Arriven** [comment]
@Luceoria not really, that errored host was using a raw ip address so no dns query was done. it was just failing to parse it locally and since local parsing is almost instant it was able to perform those tries hundreds of thousands times per second (due to the nature of the app we don't fail on error in the attack loop but just continue with the next iteration). Ideally it would be better to make some kind of distinction between such errors and network issues, but for now there's been only two issues of this type and both were rather stupid so it might be better to add some external config validation instead

**Comment by Luceoria** [comment]
Understood. I had this impression since one of the hosts from the config file does not have a DNS record, as a result I have hundreds of DNS lookups per sec and CPU usage around 30-40%. If I customize the config by removing the host entries, CPU is brought down to ~5%.

**Comment by Arriven** [comment]
@Luceoria you are using custom config for that, right? if you mainly use http jobs you can utilize `client.static_host` parameter to set predefined address and tls usage (http vs https) for a target and still have proper Host header being sent. It's not in docs yet but you can take a look at config/examples/http-host.yaml

**Comment by Luceoria** [comment]
I am using this one:
https://github.com/db1000n-coordinators/LoadTestConfig/blob/main/config.v0.7.json

Just removed the sections with "jira8.cdek.ru" since this host does not resolve. This brought the CPU usage back to normal.

**Comment by Arriven** [comment]
Hm, weird, which executable version do you use? The "static_host" feature was added in v0.8.2 and as far as I see it should be used there. If your version is up to date can you send some logs my way bc I'm out of ideas?

**Comment by Luceoria** [comment]
I use v0.8.1.

**Comment by Luceoria** [comment]
Ok, could not replicate this problem on a newest 0.8.7. Going to production.
