### ISSUE TITLE
Is adv config still relevant?

### ISSUE THREAD

**Issue by kurlyk-dev** [Arriven/db1000n#409]
Is [adv config](https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.adv.json) still relevant?
It hasn't been updated for 4 days, maybe I should switch to the common config?
But I'am running a big fleet of instances on AWS, maybe it's risky, my previous account was suspended after using common config.
WDYT?

**Comment by Arriven** [comment]
Hey, advanced config is no longer relevant as since v0.8.0 the app has a filter to disable non-advanced jobs (it's not present in default config yet because we don't use jobs that are affected)
