### ISSUE TITLE
Incorrect traffic stats calculation

### ISSUE THREAD

**Issue by asu-talk** [Arriven/db1000n#412]
With the latest version, I see that db1000n generates a lot of traffic (assume this means outgoing traffic).
But bmon shows much smaller numbers:

![image](https://user-images.githubusercontent.com/54418113/159993656-a5e3dcaf-9dac-4a7b-bff3-c80415a714a7.png)

Could you please confirm that it`s just an issue with stats calculation?

UPD: seems that this relates to the issue:
[issue 408](https://github.com/Arriven/db1000n/issues/408)

So traffic is calculated as sent but the data actually is not sent.

**Comment by Arriven** [comment]
yes, this is indeed am issue with stats calculation. This particular issue happens only with http jobs (which are the only ones being used in the config right now AFAIR). Any http request is done via an underlying tcp connection which has to be established before the request can be sent over the network (the connection can be reused between requests though). Whenever I try to send an http request through the app I just increase the metric by the size of that request but it doesn't always mean that all that data is sent over the network - if the process fails to establish connection than only small fraction of the data is actually sent (smth like 40-50 bytes out of couple hundreds that should've been sent). It's probably possible to track all those cases and change metrics appropriately but that would be a bit tedious and right now there are other priorities.
What bothers me though is that I would expect to see something like 10-50x difference between bmon and metrics but not 1000x so there should be something else cutting that traffic and I need to investigate more

**Comment by Arriven** [comment]
#408 should be already fixed for couple hours at least (although yes, that would explain that difference as the error would happen locally even before the app tries to establish the connection and I should probably detect that better)
Do you still see this behavior?

**Comment by asu-talk** [comment]
> #408 should be already fixed for couple hours at least (although yes, that would explain that difference as the error would happen locally even before the app tries to establish the connection and I should probably detect that better) Do you still see this behavior?

Thank you for your time and effort!

Yep, I still see this issue.
Version and configuration:

DB1000n [Version: v0.8.2]
Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"

OS details: Linux 5.16.0

**Comment by Arriven** [comment]
ah, ok, that one is a protocol mismatch in another recent optimization introduced to bypass this (https://github.com/Arriven/db1000n/issues/365#issuecomment-1070974009). Fixed it on the config side, will think of a way to detect it better tomorrow

**Comment by Arriven** [comment]
(it might take some time for the config to get populated to all cdn servers though)

**Comment by asu-talk** [comment]
> ah, ok, that one is a protocol mismatch in another recent optimization introduced to bypass this ([#365 (comment)](https://github.com/Arriven/db1000n/issues/365#issuecomment-1070974009)). Fixed it on the config side, will think of a way to detect it better tomorrow

Thank you!

**Comment by Arriven** [comment]
actually went ahead and fixed it today :D
https://github.com/Arriven/db1000n/commit/386944f37987fc3af60fda634b5e194ffad9f765
