### ISSUE TITLE
EnablePrimitiveJobs parameter question

### ISSUE THREAD

**Issue by localdotcom** [Arriven/db1000n#419]
I'm running db1000n on AWS EKS using helm chart. Under container log I see following message
`{"level":"info","ts":1648202330.9562292,"caller":"runner/runner.go:152","msg":"There is a filter defined for a job but this client doesn't pass it - skip the job"}`
I guess it happens because Docker image has argument `"--enable-primitive=false"` in `ENTRYPOINT` and at the same time `config.v0.7.json` defines `"filter": "{{ (.Value (ctx_key \"global\")).EnablePrimitiveJobs }}"` in section
```
{
      "type": "udp",
      "filter": "{{ (.Value (ctx_key \"global\")).EnablePrimitiveJobs }}",
      "count": 22,
      "args": {
        "address": "195.189.222.1:53",
        "body": "{{ random_payload 10 }}",
        "interval_ms": 1000
}
```
Is it expected behaviour, or should I set `--enable-primitive` to `true` for `UDP` attacks?

**Comment by Arriven** [comment]
it is expected behavior. udp jobs use a lot of traffic and are easily detected, this has led to some issues in the past (high cloud costs and people being banned bc clouds thought their machines were compromised). you can use regular image instead of advanced one if you want to utilize the full power of db1000n but do it at your own risk

**Comment by Arriven** [comment]
that being said, it's probably better to just discontinue advanced image in favor of setting this parameter in all the guides and deployments, see #421

**Comment by localdotcom** [comment]
Thank you! BTW when I'll run ~20 pod replicas will it compromised? How much pod replicas can I run safely?

**Comment by Arriven** [comment]
hard to tell, the traffic that is produced by advanced images shouldn't be qualified as DDoS without manual inspection. It kinda behaves as a misconfigured/poorly designed API at best

**Comment by localdotcom** [comment]
Thanks!
