### ISSUE TITLE
Change cloud guides and deployments to use regular image with ENABLE_PRIMITIVE=false

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#421]
I want to get rid of advanced image bc it takes more than 20 minutes to build it (compared to 3-4 minutes when building regular one with ko). It's possible to make advanced image use ko for build as well but considering all the differences between advanced and regular images (just 1 param) having different images is an overkill

**Comment by Amet13** [comment]
@Arriven does it mean that we just need to pass `ENABLE_PRIMITIVE=false` to the container as env variable?

**Comment by Arriven** [comment]
@Amet13 yes. That would also remove the need for Dockerfile
