### ISSUE TITLE
Traffic stats are not displayed

### ISSUE THREAD

**Issue by Luceoria** [Arriven/db1000n#432]
## Expected Behavior

"Traffic stats" banner displayed periodically.

## Actual Behavior

"Traffic stats" banner not displayed.
The only visible logs are:
config.go:63: Loading config from "https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"
runner.go:119: The config has not changed. Keep calm and carry on!                                                             

## Steps to Reproduce the Problem

  1. ./db1000n
  2. No traffic stats.
 

## Specifications

  - Version: v0.8.8
  - Platform: Ubuntu 20.04

**Comment by tvoretsmira** [comment]
The same behavior is observed for Windows 7 x64.

**Comment by Arriven** [comment]
Fixed in #436
The issue was there from the very beginning but only manifested now due to issues with Google analytics backend, we've changed the code to output logs regardless of that

**Comment by Luceoria** [comment]
Just tested and v0.8.9 works ok, closing.
