### ISSUE TITLE
There is no any status indication in the Console output whether an attack is successful or not

### ISSUE THREAD

**Issue by oleg-bronzhaiev** [Arriven/db1000n#433]
## Expected Behavior
**There is** some status indication in the Console output whether an attack is successful or not.
At least, this could be fixed to the indication as it was in the prev version db1000n-**v0.8.2**-windows-amd64:
"Атака проводиться успішно! Руський воєнний корабль іди нахуй!"

## Actual Behavior
**There is no** any status indication in the Console output whether an attack is successful or not:

![image](https://user-images.githubusercontent.com/26025893/160234771-5ab56bd6-d9d0-45ec-adf4-8d67bbe4b0eb.png)

## Steps to Reproduce the Problem

  1. Launch db1000n.exe
  2. Wait a few minutes

## Specifications

  - Version:     0.8.8
  - Platform:   Windows 10 Home, 64-bit
  - Subsystem:

**Comment by Arriven** [comment]
Fixed in #436
