### ISSUE TITLE
App crashed on some azure linux vw

### ISSUE THREAD

**Issue by dberezhnenko** [Arriven/db1000n#434]
When i run application with default config it halt after some target with output "Killed"
-debug option doesnt show anything.

Last attacked target could be different on several runs in row.
Problem repeated at several WM without any logic. Just today I stopped one process (which worked all nigth) and got this error after next start.

Example:
./db1000n -c ./config/config.json
...
2022/03/26 10:10:57.250146 rawnet.go:71: Attacking 185.65.22.3:3389
2022/03/26 10:10:57.260621 rawnet.go:71: Attacking 185.65.22.3:2000
Killed

Can we get more information about crash reasons?
Could we get run option -ignore_error?

## Specifications
  - Version: db1000n_0.8.8_linux_amd64.tar.gz (and 0.8.2 before)
  - Platform: Linux (ubuntu 20.04)
  - More then 450MB free RAM

Thank you!

**Comment by Arriven** [comment]
Most likely it's being killed due to OOM, you can try disabling Prometheus and encryption to decrease memory usage and leave only essential functionality. There's been an instruction in one of the issues already but tag me if you can't find it - I'll take a look when I have some more time

**Comment by dberezhnenko** [comment]
it seems your advice helpped. 
With options
-prometheus_on=false -skip-encrypted=true
app is working!
