### ISSUE TITLE
Download links in docs are broken

### ISSUE THREAD

**Issue by QyuriLa** [Arriven/db1000n#438]
## Expected Behavior

The download links work properly.

## Actual Behavoir

The download links lead you to Not Found page.

## Additional Information

Since 854f943f1964376dea4c0873fd8e10a781d663be commited, the filename scheme of released files have changed so that their version fields no longer have `v` prefix, as documented in [GoReleaser docs](https://goreleaser.com/customization/templates/?h=prefix#fn:1).

- Before: `db1000n_v0.8.3_windows_386.zip`
- After: `db1000n_0.8.4_windows_386.zip`

This change made download links in [Quickstart guide](https://arriven.github.io/db1000n/#for-dummies) unavailable, which are depend on version tags with `v` prefix as below.

- https://github.com/Arriven/db1000n/releases/download/v0.8.9/db1000n-v0.8.9-windows-386.zip (Not Found)

**Comment by Arriven** [comment]
Oops, forgot about that one, will fix shortly

**Comment by Arriven** [comment]
Should be fixed now

**Comment by QyuriLa** [comment]
Thank you!
