### ISSUE TITLE
Руський — це не правильно

### ISSUE THREAD

**Issue by adronstar** [Arriven/db1000n#447]
Руський — це не правильно, бо Руський походить від слова Русь, тобто це історично — древня Україна, до чого росія не має жодного відношення.

Краще використовувати слово "русский", або "російський", чи "московитський" 

**Русский воєнний корабль іди нахуй!** 
**Слава Україні!**

**Comment by Arriven** [comment]
Already fixed in latest release AFAIR

**Comment by Arriven** [comment]
Even better - it's fixed starting from v0.8.8
