### ISSUE TITLE
Docker compose UPDATER_MODE type problem

### ISSUE THREAD

**Issue by andser** [Arriven/db1000n#450]
## Expected Behavior
Should successfully run containers

## Actual Behavior
`
$ docker-compose -f examples/docker/static-docker-compose.yml up
ERROR: The Compose file './examples/docker/static-docker-compose.yml' is invalid because:
services.updater.environment.UPDATER_MODE contains true, which is an invalid type, it should be a string, number, or a null
`

## Steps to Reproduce the Problem

  1. Clone repo
  2. Run docker-compose -f examples/docker/static-docker-compose.yml up
  3.

## Specifications

  - Version: 0.8.10

**Comment by bitshape** [comment]
@andser you can fix by changing it to UPDATER_MODE: “true”

In other words, wrap it in quotes.
