### ISSUE TITLE
Windows version doesn't start for me

### ISSUE THREAD

**Issue by yetamzd** [Arriven/db1000n#454]
Hello! Can somebody help me please? My Windows version just doesn't work. I click on the file, it opens for a moment and then just closes. I've tried to reinstall the file for a couple of times, I've runned it with administrative rights, but nothing changed. I don't really understand all that programming stuff but just a week ago all worked pretty normal :(

**Comment by Arriven** [comment]
Can you try launching it via terminal to see the logs? You can do that by searching for "cmd" or "PowerShell" in the start menu, then dragging the executable to that window (it will input the proper path into the terminal) and pressing enter?

**Comment by yetamzd** [comment]
That's what I got: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x4 pc=0x11875aa]

goroutine 1 [running]:
main.main()
        /github/workspace/main.go:670 +0x5ca

**Comment by Arriven** [comment]
Hmm, which version are you running? The error message seems quite weird and would only be plausible if you are running something like v0.4.3 but I assume it's not the case?

**Comment by yetamzd** [comment]
I don't know for sure which version I use, because I downloaded the file by the link posted in Telegram. But I guess that's the case, because the link was posted 1 month ago. So maybe I just need to download the newest version of the file. But how can I do that without docker?

**Comment by Arriven** [comment]
You can get the latest download link at https://arriven.github.io/db1000n/

**Comment by yetamzd** [comment]
When I click on the download link, I get "Not found" error :(

**Comment by Arriven** [comment]
oops, forgot one update scenario, should be working now
