### ISSUE TITLE
Please compile for FreeBSD 13.0-RELEASE amd64

### ISSUE THREAD

**Issue by bw-development** [Arriven/db1000n#455]
There are a lot of FreeBSD users here in US, who glad to help Ukraine.
(And many of them are students and hardware technicians, so old machines also may be used. Not to forget about i386 platform ;)

Thank You and good luck!

**Comment by Arriven** [comment]
Added freebsd and bunch of other OS types (everything that compiled successfully) in 0.8.13, but can't guarantee it would work flawlessly as not enough testing was done

**Comment by bw-development** [comment]
> Added freebsd and bunch of other OS types (everything that compiled successfully) in 0.8.13, 
Thank You so much!
So, no any warnings during compilation?


> but can't guarantee it would work flawlessly as not enough testing was done
No any guarantees worldwide nowadays;)

How possible to see error/warnings log? Or how to detect any “not working as expectedl”?

Thank You for support Ukraine!

**Comment by Arriven** [comment]
Well, there's almost no OS-specific code there (I can inly recall auto update which is not a core feature) so as long as libraries support that OS there shouldn't be any problems. You could get errors from some jobs that may not work that well but as long as it doesn't crash and generates traffic it's good. You can check debug logs (--debug) for more info but errors reported by those are usually not critical.
