### ISSUE TITLE
After upgrade generated load is very very low

### ISSUE THREAD

**Issue by barnyiv** [Arriven/db1000n#457]
## Expected Behavior
100% cpu load

## Actual Behavior
1-5% cpu load

## Steps to Reproduce the Problem

  1. use 0.8.12 darwin arm64
  
Latest version that is working fine for me was 0.8.9. After upgrade to 0.8.12 issue occurred.

## Specifications

  - Version: 0.8.12
  - Platform: macos m1 pro
  - Subsystem:

**Comment by Arriven** [comment]
Most likely that 100% cpu usage was caused by a bug where the app was incorrectly handling OS limitations. Expecting 100% cpu load from the app that generates network load would be wrong as you usually hit the limit of upload speed before you hit the cpu limit. You can increase the amount of load being generated by providing `--scale <number>` parameter but be careful and monitor your network usage instead of cpu usage as it will stop growing at some point

**Comment by barnyiv** [comment]
@Arriven ok, thanks, so whats the --scale should be for maximum load? or it's different for every machine?

**Comment by localdotcom** [comment]
> @Arriven ok, thanks, so whats the --scale should be for maximum load? or it's different for every machine?

It depends on number of CPU and memory size.

**Comment by barnyiv** [comment]
Ok, I've just tried with --scale [16, 32, 64, 128]
For 1 m each
it generated --------------> [104, 209, 411, 750] mbs of traffic respectively

should I just crank it up even more? I don't understand if that's actually effective.

**Comment by Arriven** [comment]
It depends, the easiest way would be to compare response rate. If it goes down by a noticeable percentage after you increased the scale - most likely you've hit the limit
Also be aware that a lot of sites may have protection that limits the amount of requests per second from a single IP so even if you are able to generate more load the effectiveness of that additional load may be lower. That's one of the main reasons we have low defaults - it's better to have more machines that generate smaller load than to generate higher load per machine while not being able to run it on lower end machines.

**Comment by barnyiv** [comment]
Response rate is 0%, doesn't matter at what scale.

**Comment by Arriven** [comment]
Seems like current default targets changed their IP addresses and started using qrator, in this case scaling the app won't really help until we switch targets
