### ISSUE TITLE
C/C++ port

### ISSUE THREAD

**Issue by oxbee** [Arriven/db1000n#463]
Let's say I have shell (SSH) access to device which would like to execute db1000n. But unfortunately nor docker or GO is available there.
Thus, I would like to port db1000n into platform dependent executable via gcc / g++ compilation.
Since i'm only C/C++ developer and know nothing about GO, i would like to check if it would be possible to apply [this](https://stackoverflow.com/questions/62977352/using-go-in-c) manual to entire project?

Any hints and ideas highly appreciated.

**Comment by oxbee** [comment]
Ok, after checking documentation I've found this magnificent  [link](https://github.com/Arriven/db1000n/releases/latest)

**Comment by Arriven** [comment]
I wish I could see your reaction when you find shell install script I crafted specifically for that case :)
https://github.com/Arriven/db1000n/blob/main/docs/advanced-docs/advanced-and-devs.md
