### ISSUE TITLE
Crash on DigitalOcean droplet

### ISSUE THREAD

**Issue by AndriiNytsyk** [Arriven/db1000n#47]
Tool crashes on DigitalOcean droplet (Shared CPU, 2 vCPUs, 4 GB, 25 GB, 4 TB). Startup method: docker install.

goroutine 44381 [running]:
math/rand.(*Rand).Intn(0x80acea, 0x46817b)
        /usr/local/go/src/math/rand/rand.go:168 +0x65
math/rand.Intn(...)
        /usr/local/go/src/math/rand/rand.go:337
main.httpJob.func1(0xc003364d00)
        /usr/src/app/main.go:229 +0x45
net/http.(*Transport).connectMethodForRequest(0xc00d50ab40, 0xc00d23d2c0)
        /usr/local/go/src/net/http/transport.go:834 +0x91
net/http.(*Transport).roundTrip(0xc00d50ab40, 0xc003364d00)
        /usr/local/go/src/net/http/transport.go:571 +0x6c5
net/http.(*Transport).RoundTrip(0xc003364d00, 0x8d2480)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc003364c00, {0x8d2480, 0xc00d50ab40}, {0x7fe120, 0x48a501, 0xbb6680})
        /usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc00e272c00, 0xc003364c00, {0xc00e273c20, 0x2f, 0xbb6680})
        /usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc00e272c00, 0xc003364c00)
        /usr/local/go/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
main.httpJob({0x8db078, 0xc002cb5b80}, 0xc0000a6310, {0xc00230e1e0, 0x9a, 0xa0})
        /usr/src/app/main.go:282 +0xa9e
created by main.main
        /usr/src/app/main.go:586 +0x725

P.S. In Droplets with worse characteristics tool is killed by OOM-killer.

**Comment by Arriven** [comment]
@AndriiNytsyk Can you send the config you are using in case it's not default?

**Comment by AndriiNytsyk** [comment]
I use default configuration according to instruction "docker install".

**Comment by scamp** [comment]
Please add swapfile:
 dd if=/dev/zero of=/swapfile bs=1M count=1024
 mkswap /swapfile
 chmod 600 /swapfile
 swapon /swapfile

**Comment by AndriiNytsyk** [comment]
I've checked proposed solution but it didn't help. Swap size range I used: 600 MB - 8 GB

panic: invalid argument to Intn                                                                               

goroutine 30540 [running]:
math/rand.(*Rand).Intn(0x80acea, 0x46817b)
        /usr/local/go/src/math/rand/rand.go:168 +0x65
math/rand.Intn(...)
        /usr/local/go/src/math/rand/rand.go:337
main.httpJob.func1(0xc000dde500)
        /usr/src/app/main.go:229 +0x45
net/http.(*Transport).connectMethodForRequest(0xc001669040, 0xc00312c600)
        /usr/local/go/src/net/http/transport.go:834 +0x91
net/http.(*Transport).roundTrip(0xc001669040, 0xc000dde400)
        /usr/local/go/src/net/http/transport.go:571 +0x6c5
net/http.(*Transport).RoundTrip(0xc000dde400, 0x8d2480)
        /usr/local/go/src/net/http/roundtrip.go:18 +0x19
net/http.send(0xc000dde300, {0x8d2480, 0xc001669040}, {0x7fe120, 0x48a501, 0xbb6680})
        /usr/local/go/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc001d07920, 0xc000dde300, {0xc00312c500, 0x8d26e0, 0xbb6680})
        /usr/local/go/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc001d07920, 0xc000dde300)
        /usr/local/go/src/net/http/client.go:725 +0x908
net/http.(*Client).Do(...)
        /usr/local/go/src/net/http/client.go:593
main.httpJob({0x8db078, 0xc002f05300}, 0xc0000a6310, {0xc002ecc200, 0x1e6, 0x200})
        /usr/src/app/main.go:282 +0xa9e
created by main.main
        /usr/src/app/main.go:586 +0x725

**Comment by Arriven** [comment]
ok, I guess I know what's happening, I didn't consider the case when proxylist is a valid json but has no proxy entries in it, should be easy to fix

**Comment by Arriven** [comment]
@AndriiNytsyk check v0.5.8, although it shouldn't have been crashing since some earlier release (checking which one rn)

**Comment by AndriiNytsyk** [comment]
Fixed on v0.5.8.
Thanks!
