### ISSUE TITLE
Proxy not work for Windows

### ISSUE THREAD

**Issue by OleksandrBlack** [arriven/db1000n#475]
## Expected Behavior
![work](https://user-images.githubusercontent.com/13917465/161261358-b0e21332-6863-46b9-b33e-a0594bb084ec.jpg)

## Actual Behavior
![win_error](https://user-images.githubusercontent.com/13917465/161260849-28f14f9c-7530-4ffc-be32-7ff2dc58fa87.jpg)

## Steps to Reproduce the Problem

  .\db1000n.exe --proxy '{{ join (split (get_url "https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt") "\n") "," }}'

## Specifications

  - Version: 0.8.15
  - Platform: Windows 10 x64
https://github.com/Arriven/db1000n/issues/424

**Comment by HongKilDong** [comment]
I have the same issue on ubuntu

**Comment by Arriven** [comment]
Could you try it in powershell? I'm not an expert in windows commandline syntax so in case PowerShell doesn't work we'd need someone who's experienced in it to have a look on how to properly escape the sequence

**Comment by PerchunPak** [comment]
Same thing in docker
`docker run -d --name db1000n ghcr.io/arriven/db1000n --proxy '{{ join (split (get_url "https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt") "\n") "," }}'`

**Comment by PerchunPak** [comment]
Fixed it by specify `--proxy "{{ join (split (get_url \"https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt\") \"\n\") \",\" }}"` (replace all `"` with `\"` and replace `'` to `"` in start and end of argument).

[See how specify argument with spaces in Windows.](https://stackoverflow.com/questions/473117/pass-path-with-spaces-as-parameter-to-bat-file)

**Comment by OleksandrBlack** [comment]
> 

![err2](https://user-images.githubusercontent.com/13917465/161477768-a2102251-a181-49f0-9c15-e1db3e2cef1a.jpg)
Not work @Arriven 

can be simplified? just provide a link --proxylist https://raw.githubusercontent.com/porthole-ascend-cinnamon/proxy_scraper/main/proxies.txt

**Comment by vasyl-bhd** [comment]
Hi! 
Have the same issue on my Digital Ocean instance. Is there any way to type country manually, OR bypass this check somehow?
