### ISSUE TITLE
introduce timeout job

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#482]
more tools to make complex scenarios

**Comment by oherych** [comment]
Can you please provide some examples?

**Comment by Arriven** [comment]
You can find some utility jobs in `src/job/util.go` and use them as a reference

**Comment by Arriven** [comment]
fixed by https://github.com/Arriven/db1000n/commit/ccecdf8e628af2e35b1c50987c43b19a90cb5c8e
