### ISSUE TITLE
Add DNS protocol support to packetgen jobs

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#49]
see https://pkg.go.dev/github.com/google/gopacket/layers#DNS for reference

**Comment by alexdanger** [comment]
@Arriven is still relevant? if yes, could add a bit more details, thanks.

**Comment by Arriven** [comment]
@alexdanger yes, it's still relevant in terms of packetgen. That module is intended to be able to generate any kind of network packets based on the configuration and it would be good to add support of various protocols to it. See https://pkg.go.dev/github.com/google/gopacket/layers#DNS for DNS reference of gopacket/layers which I use for tcp/udp/ip/ethernet frames generation. There's also a task to add icmp support there (ideally v6) #360
