### ISSUE TITLE
Errors. Version 0.8.18

### ISSUE THREAD

**Issue by udjfvnsaoepna** [Arriven/db1000n#492]
Errors.
**Windows 10**
Version **0.8.18**
Start by: db1000n.exe --proxy http://***.***.***.***/proxy.txt --scale 10
Proxy format user:password@ip:port

**Update**: checked version **0.8.17**, also with errors

```
goroutine 25329 [semacquire, 1 minutes]:
sync.runtime_SemacquireMutex(0x10?, 0x6?, 0xdef153?)
        /opt/hostedtoolcache/go/1.18.0/x64/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc00006a050)
        /opt/hostedtoolcache/go/1.18.0/x64/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
        /opt/hostedtoolcache/go/1.18.0/x64/src/sync/mutex.go:81
log.(*Logger).Output(0xc00006a050, 0xc?, {0xc015ee5bc0, 0x1d})
        /opt/hostedtoolcache/go/1.18.0/x64/src/log/log.go:176 +0x9c
log.Printf({0x161b941?, 0x14f84e0?}, {0xc027b43c80?, 0x4?, 0x0?})
        /opt/hostedtoolcache/go/1.18.0/x64/src/log/log.go:351 +0x55
github.com/Arriven/db1000n/src/job.fastHTTPJob({0x177e9c0?, 0xc01628e930?}, 0x0?, 0xc0002e6140, 0x0?)
        /home/runner/work/db1000n/db1000n/src/job/http.go:147 +0x5df
github.com/Arriven/db1000n/src/job.(*Runner).runJobs.func1(0x7)
```

**Comment by Arriven** [comment]
hmm, not yet sure about the error but there are couple things wrong with your proxy setup that are not related to that:

1. proxy format should include protocol, not only host:port pair (good examples would be `http://user:password@ip:port` or `socks5://user:password@ip:port`)
2. `--proxy` expects either a comma-separated list of proxies or a template instruction on how to get that list (see [example](https://github.com/Arriven/db1000n/discussions/466#discussioncomment-2475729) of usage)

**Comment by Arriven** [comment]
can you try running it without those commandline arguments to see if they are affecting the behavior in any way? (also if you would be able to determine which exact combination of args leads to this error it could help debugging)
