### ISSUE TITLE
Zero requests sent

### ISSUE THREAD

**Issue by sash-ko** [Arriven/db1000n#510]
How can I check that db1000n actually sends requests? "Traffic stats" shows that the number of requests sent is always zero but the number of requests attempted is higher than zero. I see the same results no matter how I run it - with or without VPN, from the command line or as a Docker container, from my laptop, or from a digitalocean instance.

**Comment by Arriven** [comment]
Right now it seems like the targets are using some heavy geo blocking and I don't think we can do anything about it, admins are evaluating whether it's better to continue or change the target

**Comment by sash-ko** [comment]
Thank you for the quick answer
