### ISSUE TITLE
Please add possibility to configure multipart/form-data request from config

### ISSUE THREAD

**Issue by Vitalii-Gozhenko** [Arriven/db1000n#512]
It would be nice to have possibility to config `multipart/form-data` requests from config. Currently it is not possible because there is no possibility to insert newline character into the body

**Comment by Arriven** [comment]
Hmm, it should be possible to input newline characters to both json and yaml which are accepted formats here but I'll take a look tomorrow

**Comment by Arriven** [comment]
yup, it does work, you can probably take look here for examples on how to specify multiline strings in yaml https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines
