### ISSUE TITLE
v0.8.29: Docker version exits after printing out config

### ISSUE THREAD

**Issue by 5har0varik** [Arriven/db1000n#515]
## Expected Behavior
Normal work, regular updates with stats and russian warship go fuck yourself

## Actual Behavior
After printing out config process exit with no error
`root@ubuntu-s-1vcpu-1gb-ams3-01:~# docker run --rm -it --pull always --network host ghcr.io/arriven/db1000n
latest: Pulling from arriven/db1000n
Digest: sha256:b051ec35f5cbc9633487d3e131240e2c7a4e889938f617335801664483e6db22
Status: Image is up to date for ghcr.io/arriven/db1000n:latest
{"level":"info","ts":1650705424.5453908,"caller":"db1000n/main.go:67","msg":"running db1000n","version":"v0.8.29","pid":1}
{"level":"info","ts":1650705424.549451,"caller":"utils/countrychecker.go:58","msg":"checking IP address,","iter":1}
{"level":"info","ts":1650705424.6822293,"caller":"utils/countrychecker.go:78","msg":"location info","country":"Netherlands","ip":"164.90.193.145"}
{"level":"info","ts":1650705424.7504263,"caller":"config/config.go:75","msg":"loading config","path":"https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.v0.7.json"}
{"level":"info","ts":1650705424.7585795,"caller":"job/runner.go:100","msg":"new config received, applying"}
{"level":"warn","ts":1650705424.7603846,"caller":"job/runner.go:168","msg":"unknown job","type":""}
{"level":"info","ts":1650705424.763096,"caller":"job/runner.go:204","msg":"job instances (re)started","count":873}
{"level":"info","ts":1650705424.7649148,"caller":"job/http.go:148","msg":"attacking","target":"https://its.1c.ru"}
{"level":"info","ts":1650705424.7669027,"caller":"job/http.go:148","msg":"attacking","target":"https://its.1c.ru"}
{"level":"info","ts":1650705424.7682576,"caller":"job/http.go:148","msg":"attacking","target":"https://its.1c.ru"}
{"level":"info","ts":1650705424.7696784,"caller":"job/http.go:148","msg":"attacking","target":"https://its.1c.ru"}
{"level":"info","ts":1650705424.7709334,"caller":"job/http.go:148","msg":"attacking","target":"https://its.1c.ru"}
{"level":"info","ts":1650705424.7722645,"caller":"job/http.go:148","msg":"attacking","target":"http://v8.1c.ru"}
{"level":"info","ts":1650705424.7734246,"caller":"job/http.go:148","msg":"attacking","target":"http://v8.1c.ru"}
{"level":"info","ts":1650705424.7745802,"caller":"job/http.go:148","msg":"attacking","target":"http://v8.1c.ru"}
{"level":"info","ts":1650705424.775639,"caller":"job/http.go:148","msg":"attacking","target":"https://update.rarus.ru/public"}
{"level":"info","ts":1650705424.8138149,"caller":"job/http.go:148","msg":"attacking","target":"http://techlab.rarus.ru"}{"level":"info","ts":1650705424.815206,"caller":"job/http.go:148","msg":"attacking","target":"http://techlab.rarus.ru"}
{"level":"info","ts":1650705424.8167198,"caller":"job/http.go:148","msg":"attacking","target":"http://techlab.rarus.ru"}{"level":"info","ts":1650705424.8180747,"caller":"job/http.go:148","msg":"attacking","target":"https://techlab.rarus.ru"}
{"level":"info","ts":1650705424.819535,"caller":"job/http.go:148","msg":"attacking","target":"https://techlab.rarus.ru"}{"level":"info","ts":1650705424.820882,"caller":"job/http.go:148","msg":"attacking","target":"https://techlab.rarus.ru"}{"level":"info","ts":1650705424.8220897,"caller":"job/http.go:148","msg":"attacking","target":"https://techlab.rarus.ru"}
{"level":"info","ts":1650705424.8232696,"caller":"job/http.go:148","msg":"attacking","target":"https://techlab.rarus.ru"}
{"level":"info","ts":1650705424.8243272,"caller":"job/http.go:148","msg":"attacking","target":"https://techlab.rarus.ru"}
{"level":"info","ts":1650705424.8254263,"caller":"job/http.go:148","msg":"attacking","target":"https://techlab.rarus.ru"}
{"level":"info","ts":1650705424.8265016,"caller":"job/http.go:148","msg":"attacking","target":"http://bo.rarus.ru"}
{"level":"info","ts":1650705424.827545,"caller":"job/http.go:148","msg":"attacking","target":"http://bo.rarus.ru"}
{"level":"info","ts":1650705424.8286319,"caller":"job/http.go:148","msg":"attacking","target":"http://bo.rarus.ru"}
{"level":"info","ts":1650705424.8297927,"caller":"job/http.go:148","msg":"attacking","target":"http://bo.rarus.ru"}
{"level":"info","ts":1650705424.8308933,"caller":"job/http.go:148","msg":"attacking","target":"http://bo.rarus.ru"}
{"level":"info","ts":1650705424.8319821,"caller":"job/http.go:148","msg":"attacking","target":"http://bo.rarus.ru"}
{"level":"info","ts":1650705424.833139,"caller":"job/http.go:148","msg":"attacking","target":"http://bo.rarus.ru"}
{"level":"info","ts":1650705424.8342435,"caller":"job/http.go:148","msg":"attacking","target":"https://bo.rarus.ru"}
{"level":"info","ts":1650705424.8353512,"caller":"job/http.go:148","msg":"attacking","target":"https://bo.rarus.ru"}
{"level":"info","ts":1650705424.8364265,"caller":"job/http.go:148","msg":"attacking","target":"https://bo.rarus.ru"}
{"level":"info","ts":1650705424.837566,"caller":"job/http.go:148","msg":"attacking","target":"https://bo.rarus.ru"}
{"level":"info","ts":1650705424.8387067,"caller":"job/http.go:148","msg":"attacking","target":"https://bo.rarus.ru"}
{"level":"info","ts":1650705424.8396642,"caller":"job/http.go:148","msg":"attacking","target":"https://bo.rarus.ru"}
{"level":"info","ts":1650705424.84095,"caller":"job/http.go:148","msg":"attacking","target":"https://bo.rarus.ru"}
{"level":"info","ts":1650705424.842246,"caller":"job/http.go:148","msg":"attacking","target":"http://pos.rarus.ru"}
{"level":"info","ts":1650705424.843645,"caller":"job/http.go:148","msg":"attacking","target":"http://pos.rarus.ru"}
{"level":"info","ts":1650705424.844986,"caller":"job/http.go:148","msg":"attacking","target":"http://pos.rarus.ru"}
{"level":"info","ts":1650705424.846288,"caller":"job/http.go:148","msg":"attacking","target":"http://pos.rarus.ru"}
{"level":"info","ts":1650705424.8476028,"caller":"job/http.go:148","msg":"attacking","target":"http://pos.rarus.ru"}
{"level":"info","ts":1650705424.8487954,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8497734,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8507857,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8517323,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8527486,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.853628,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.854521,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8557854,"caller":"job/http.go:148","msg":"attacking","target":"https://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8574235,"caller":"job/http.go:148","msg":"attacking","target":"https://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8587549,"caller":"job/http.go:148","msg":"attacking","target":"https://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.859998,"caller":"job/http.go:148","msg":"attacking","target":"https://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8612165,"caller":"job/http.go:148","msg":"attacking","target":"https://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8622396,"caller":"job/http.go:148","msg":"attacking","target":"https://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8632016,"caller":"job/http.go:148","msg":"attacking","target":"https://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8642228,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8653977,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.866357,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8674133,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8684497,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8697534,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.871013,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.872243,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8737185,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8748126,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8757913,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8768044,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8777065,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8786514,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8795934,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8804429,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8813193,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8820605,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.882856,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.883722,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8847063,"caller":"job/http.go:148","msg":"attacking","target":"http://regservice.keydisk.ru"}
{"level":"info","ts":1650705424.8855157,"caller":"job/http.go:148","msg":"attacking","target":"http://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.886393,"caller":"job/http.go:148","msg":"attacking","target":"http://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8873267,"caller":"job/http.go:148","msg":"attacking","target":"http://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.888291,"caller":"job/http.go:148","msg":"attacking","target":"http://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8893332,"caller":"job/http.go:148","msg":"attacking","target":"https://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8901174,"caller":"job/http.go:148","msg":"attacking","target":"https://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8911037,"caller":"job/http.go:148","msg":"attacking","target":"https://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8920746,"caller":"job/http.go:148","msg":"attacking","target":"https://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8929927,"caller":"job/http.go:148","msg":"attacking","target":"https://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8939188,"caller":"job/http.go:148","msg":"attacking","target":"https://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.8947878,"caller":"job/http.go:148","msg":"attacking","target":"https://service.alcolicenziat.ru/auth/login"}
{"level":"info","ts":1650705424.896114,"caller":"job/http.go:148","msg":"attacking","target":"http://f4.fss.ru"}
{"level":"info","ts":1650705424.89723,"caller":"job/http.go:148","msg":"attacking","target":"http://f4.fss.ru"}
{"level":"info","ts":1650705424.8983583,"caller":"job/http.go:148","msg":"attacking","target":"http://f4.fss.ru"}
{"level":"info","ts":1650705424.8996167,"caller":"job/http.go:148","msg":"attacking","target":"http://f4.fss.ru"}
{"level":"info","ts":1650705424.9006946,"caller":"job/http.go:148","msg":"attacking","target":"http://f4.fss.ru"}
{"level":"info","ts":1650705424.901705,"caller":"job/http.go:148","msg":"attacking","target":"http://f4.fss.ru"}
{"level":"info","ts":1650705424.9025996,"caller":"job/http.go:148","msg":"attacking","target":"http://f4.fss.ru"}
{"level":"info","ts":1650705424.9036884,"caller":"job/http.go:148","msg":"attacking","target":"https://f4.fss.ru"}
{"level":"info","ts":1650705424.9046319,"caller":"job/http.go:148","msg":"attacking","target":"https://f4.fss.ru"}
{"level":"info","ts":1650705424.905421,"caller":"job/http.go:148","msg":"attacking","target":"https://f4.fss.ru"}
{"level":"info","ts":1650705424.9063344,"caller":"job/http.go:148","msg":"attacking","target":"https://f4.fss.ru"}
{"level":"info","ts":1650705424.9072802,"caller":"job/http.go:148","msg":"attacking","target":"https://f4.fss.ru"}
{"level":"info","ts":1650705424.9082866,"caller":"job/http.go:148","msg":"attacking","target":"https://f4.fss.ru"}
{"level":"info","ts":1650705424.9115968,"caller":"job/http.go:148","msg":"attacking","target":"https://f4.fss.ru"}
{"level":"info","ts":1650705424.9131806,"caller":"job/http.go:148","msg":"attacking","target":"http://docs.fss.ru"}
{"level":"info","ts":1650705424.9144766,"caller":"job/http.go:148","msg":"attacking","target":"http://docs.fss.ru"}
{"level":"info","ts":1650705424.981424,"caller":"job/http.go:148","msg":"attacking","target":"http://ca.fsrar.ru"}
{"level":"info","ts":1650705425.0527554,"caller":"job/http.go:148","msg":"attacking","target":"http://report.keydisk.ru"}
{"level":"info","ts":1650705425.1046236,"caller":"job/http.go:148","msg":"attacking","target":"http://lk.fss.ru"}
{"level":"info","ts":1650705425.1759644,"caller":"job/http.go:148","msg":"attacking","target":"https://eln.fss.ru"}
{"level":"info","ts":1650705425.2315886,"caller":"job/http.go:148","msg":"attacking","target":"http://online.1c.ru/catalog/products"}
root@ubuntu-s-1vcpu-1gb-ams3-01:~#`

## Steps to Reproduce the Problem

  1. execute docker run --rm -it --pull always --network host ghcr.io/arriven/db1000n

## Specifications

  - Version: v0.8.29
  - Platform: Ubuntu 20.04.3
  - Subsystem: DigitalOcean droplet

**Comment by Arriven** [comment]
How much memory is available to the container?

**Comment by Arriven** [comment]
Actually I've got an idea on how to fix that high memory usage, should be working with less than 500mb memory available once 0.8.30 finishes building (shouldn't take more than 10 minutes)

**Comment by 5har0varik** [comment]
> How much memory is available to the container?

That's 1GB container. Once I was able to proceed to attack but no more.

**Comment by 5har0varik** [comment]
> Actually I've got an idea on how to fix that high memory usage, should be working with less than 500mb memory available once 0.8.30 finishes building (shouldn't take more than 10 minutes)

Looks good now, lets see 4 a while

**Comment by 5har0varik** [comment]
Looks like resolved: attack go on, but during config print there are lines:
`{"level":"warn","ts":1650718985.1054173,"caller":"templates/templates.go:175","msg":"error executing template","error":"template: tpl:1:17: executing \"tpl\" at <index (split (.Value (ctx_key \"data.source\")) \"function() {\") 1>: error calling index: reflect: slice index out of range"}
{"level":"info","ts":1650718985.1082087,"caller":"job/http.go:69","msg":"single http request","target":"https://www.cryptopro.ru/"}
{"level":"warn","ts":1650718985.2341616,"caller":"templates/templates.go:175","msg":"error executing template","error":"template: tpl:1:17: executing \"tpl\" at <index (split (.Value (ctx_key \"data.source\")) \"function() {\") 1>: error calling index: reflect: slice index out of range"}`
