### ISSUE TITLE
[Question to Developers/Maintainers] Is db1000nX100 considered as trusted rework of db1000n ?

### ISSUE THREAD

**Issue by dannysilence** [Arriven/db1000n#527]
Hello there.

Was quiet impressed to read the description of this (https://github.com/ihorlv/db1000nX100), but feeling tentative about to which side of the force it belongs to, considering the fact what db1000n is doing and how easy it is to use it in some form of opposite direction or simply to compromise. 

Please let me know how trustfully can we be to that fork/rework of db1000n. 

Maybe anyone from the developers already took a look or participated/reviewed/helped that guy.

Thanks!

**Comment by Arriven** [comment]
Yes, it's trustworthy.

You can see the reference to that repo on official itarmy website (https://itarmy.com.ua/powerful/?lang=en) and some of the db1000n features were even added by request of db1000nX100 author. I should probably leave a reference to that repo somewhere in my repo to make it more clear but I haven't decided where to put it yet

**Comment by dannysilence** [comment]
that may definitely help if anyone would have similar question in future as it looks like there were no references from quick look around as i thought yesterday
