### ISSUE TITLE
SkipBody - what it really does?

### ISSUE THREAD

**Issue by deputinizer** [Arriven/db1000n#534]
Well, SkipBody does something different I think. 
```golang
resp.SkipBody = true
```
https://github.com/Arriven/db1000n/commit/3147170641eb0c3da75cfc74d68d9606d4e23d5a

The server sends body response but we are ignoring it, thus mishandling the HTTP protocol.
https://github.com/valyala/fasthttp/blob/7cc6f4c513f9e0d3686142e0a1a5aa2f76b3194a/http.go#L1305

I suppose what you really wanted is like:
```golang
resp.DiscardBody = true
```
https://github.com/erkexzcx/stoppropaganda/blob/main/internal/stoppropaganda/websites.go#L286

I've already implemented it in stoppropaganda by editing fasthttp.
https://github.com/deputinizer/fasthttp/commits/master

I'm open to discussion, maybe I'm wrong... but HTTP protocol is pretty simple I think. :wink:

**Comment by Arriven** [comment]
the idea was to have a way to utilize cpu better by not needing to do unnecessary work if the goal is to just spam the target with traffic. I then realized that it's better done by utilizing packetgen but forgot to remove this part, thanks for reminding!
