### ISSUE TITLE
SIGSEGV incoming

### ISSUE THREAD

**Issue by deputinizer** [Arriven/db1000n#537]
This will cause memory issues. Nil pointer dereference probably
```golang
req := fasthttp.AcquireRequest()
fasthttp.ReleaseRequest(req)
// using req later
```

https://github.com/Arriven/db1000n/blob/12b3db0d757d3bdcb83ff3b893555c6db6870a98/src/job/http.go#L149

**Comment by Arriven** [comment]
ah, right. It doesn't cause SIGSEGV as it just returns the request to the pool, but it probably reuses it between different goroutines making a mess anyway

**Comment by deputinizer** [comment]
It caused SIGSEGV in stoppropaganda :rofl:

**Comment by Arriven** [comment]
hmm, I've quickly run through the source of that pool and I'm not sure I see anything that could lead to a crash except race detection. Anyway that's not a good code and I fixed it already
