### ISSUE TITLE
Things to optimize - performance

### ISSUE THREAD

**Issue by deputinizer** [arriven/db1000n#539]
- utils.Decode
- templates.Parse
- job.getNextPacket

<details>
  <summary>[Spoiler] pprof CPU</summary>
  

![image](https://user-images.githubusercontent.com/100740281/167301028-f716191c-ba1b-4dbe-8498-2b133b79e9b1.png)

![image](https://user-images.githubusercontent.com/100740281/167301430-cf73f8ca-56b8-4a10-bb30-aaddbbd2fc45.png)

![image](https://user-images.githubusercontent.com/100740281/167301489-83bd7141-e065-49c1-b84b-5b730408e7bf.png)

![image](https://user-images.githubusercontent.com/100740281/167301568-aef33cb1-bc70-4d69-aeb6-443a1358ee73.png)

</details>

**Comment by Arriven** [comment]
for `getNextPacket`: have you tried setting `StaticPacket` to true in the config? should work on tcp/udp jobs as well as they just forward that argument to packetgen

**Comment by deputinizer** [comment]
Well I'm using the default config.
https://github.com/db1000n-coordinators/LoadTestConfig/blob/e3ed4702c7d19347668ac5842d058172b596c329/config.v0.7.json#L435

There's no `StaticPacket` there

**Comment by Arriven** [comment]
I'm not sure you can optimize other two without defeating their purpose completely. The only other thing that could be done is porting that StaticPacket thing to http flood to enable sending more traffic when no variablility is needed

**Comment by deputinizer** [comment]
Well there should be something faster, maybe:
- just pure `function` and `arg` (`random_payload 10`)
- JIT - just in time compiled template? Is there anything in go?

**Comment by deputinizer** [comment]
Because compiling config is a no-go? :yum: 
https://github.com/valyala/quicktemplate

**Comment by Arriven** [comment]
pure `function` and `arg` could work, but it would make the config even more bloated and I'm not completely sure it would be much faster, especially compared to `static` version which parses templates only once when new config is received. Also current implementation is already not that bad - in go you have separate `Parse` and `Execute` functions for templates where `Parse` takes significantly more resources than `Execute`. I don't think it's the most effective implementation but it does its job quite well

**Comment by Arriven** [comment]
> There's no StaticPacket there

Yeah, updating all the admin processes takes some time

**Comment by deputinizer** [comment]
Nice, you added static :)

<details>
  <summary>[Spoiler] Here's dynamic</summary>

![image](https://user-images.githubusercontent.com/100740281/167306967-29e88664-4584-4b51-94ae-da01db709980.png)
</details>

**Comment by Arriven** [comment]
hmm, having thought about it more, with current usage it might be easier to switch the code to use static by default and dynamic would have to be specified explicitly

**Comment by Arriven** [comment]
it won't affect memory usage but the CPU profile should get a lot better
