### ISSUE TITLE
Unusable on cloud servers (OOM)

### ISSUE THREAD

**Issue by mik9** [Arriven/db1000n#54]
Eats 1Gb RAM in few seconds and hangs machine.
Tried running docker image on Linux.

**Comment by MaxGenash** [comment]
The same for me:
```
2022/03/03 14:35:55 178.248.236.218 is already an IP address, skipping DNS resolution
2022/03/03 14:35:55 178.248.236.218 is already an IP address, skipping DNS resolution
Killed
```

**Comment by artemkomyshan** [comment]
Same for me with the manual build and run.

**Comment by jdoe7865623** [comment]
Works on machines with 2GB RAM. At 1GB indeed gets killed on OOM. Until this is fixed, stick to 2 GB machines.

**Comment by Arriven** [comment]
Considering that there are workarounds I'll set a low priority to this issue for now. If you want to help with debugging this you can consider creating custom configs that only use single job and see how much resources they use - I think that the amount of RAM is directly proportional to the amount of jobs used. Another possible explanation could be that the OS needs to allocate some RAM to store all the packets that program has generated but the OS didn't have a chance to send yet, I'm not fully aware of the mechanism there yet but that can be checked by using rate limiting for jobs (also requires custom configs)

**Comment by b0nn1e** [comment]
What is the best VPS configuration for this docker image?

**Comment by b0nn1e** [comment]
Works good with 3 CPU 4 GB RAM

**Comment by iffixit** [comment]
> 

use container instances instead
