### ISSUE TITLE
Reference to db1000nX100 project

### ISSUE THREAD

**Issue by avoylenko** [arriven/db1000n#540]
Hello all,

Running a single instance of db1000n requires extra maintenance cost since IP could be banned/blocked temporary really fast and the instance becoming not effective. There is a really good project(https://github.com/ihorlv/db1000nX100) based on db1000n that solves this problem by running N number of VPN tunnels and rotates between them based on uploaded OVPN configs. 

Could the reference to this project added somewhere in the repo?

**Comment by vitich** [comment]
https://itarmy.com.ua/instruction/#db1000n 
Close the task pls
