### ISSUE TITLE
Disk usage is increasing with Docker containers

### ISSUE THREAD

**Issue by MetaMmodern** [arriven/db1000n#550]
## Expected Behavior

Disk usage remains the same from update to update.

## Actual Behavior
Disk usage is increasing. I guess this is happening because of some docker caching and layers in Dockerfile are not written correctly, so cache update is huge.
Graph is for last 14 days of work.
![image](https://user-images.githubusercontent.com/42899786/171938134-86d97838-a38d-42be-9a97-b19f85c1daff.png)

## Steps to Reproduce the Problem

  1. run 2-3 instances of docker image using `docker run -d --rm -it --pull always --network host ghcr.io/arriven/db1000n`
  2. wait for several days, wait for updates I guess.
  3. check disk usage graphs.

## Specifications

  - Version: latest(?)
  - Platform: DigitalOcean
  - Subsystem: Ubuntu

**Comment by arriven** [comment]
I don't think this is something I can fix on my end. This is just the way docker works (it keeps all the older versions of images even if you don't use those). You can clean the system up by using `docker system prune` periodically which should remove unused data. Depending on your setup you can opt into running that command periodically with some cron or run it on every deploy but usually running that once in a while is enough

I'm also working on a side project that will allow using single image to run and auto-update db1000n in different environments (including containers) but it's not ready yet

**Comment by MetaMmodern** [comment]
> in different environments
@arriven what do you mean by this? Sounds cool, however it's already possible to update db1000n without killing the container.

**Comment by arriven** [comment]
AFAIR, the only layer that changes between versions is the one where the executable resides and I doubt it'll be possible to cache that

**Comment by arriven** [comment]
As for updates: docker tracks the container lifetime by existance of the process with PID 1. Any kind of version update requires to restart the process in order to update the code and the new process won't get the same id as old one. In order to get around that you need to use some external process as the controller and that's what I'm planning to do

**Comment by MetaMmodern** [comment]
Okay, I'll close this for how then. Thank you
