### ISSUE TITLE
prometheus.go:298: Can't push metrics to gateway

### ISSUE THREAD

**Issue by wips** [arriven/db1000n#556]
## Expected Behavior
No error

## Actual Behavior
2022/06/25 19:31:16.934473 prometheus.go:298: Can't push metrics to gateway, trying to change gateway

## Steps to Reproduce the Problem

  1. Run db1000n_0.8.7_darwin_amd64 in mac terminal
  2. Observe logs

## Specifications

  - Version: 0.8.7
  - Platform: Mac
  - Subsystem: macOS BigSur 11.6.7

**Comment by wips** [comment]
duplicate

**Comment by arriven** [comment]
For this one you can just update to latest
