### ISSUE TITLE
Add new sites?

### ISSUE THREAD

**Issue by VanHoevenTR** [arriven/db1000n#561]
Sorry if this is wrong place to ask, but can these sites `89.191.237.192`, `rttv.ru` and `rttv.co.uk` be added to list? These don't have DDOS protection from what I know.

RT is the biggest propaganda and it seems IT army or anonymous no longer interested since RT added ddos protection on main domain `rt.com`

**Comment by vitich** [comment]
Hi. Go to https://itarmy.com.ua/instruction/?lang=en and press the big button "@Suggest Targets" at the top right.
