### ISSUE TITLE
Non-cumulative stats

### ISSUE THREAD

**Issue by Luceoria** [arriven/db1000n#563]
I use the -less-stats option and it is working great. Is there any option (or implementation possibility) to display a non-cumulative stats once a minute, like requests and Mb per second? Right now the counters are accumulated every minute and total number is displayed.

**Comment by arriven** [comment]
version 0.9.15 now outputs both cumulative and non-cumulative stats in format `(stat since last refresh)/(total stat)`. if you use json or console format instead of simple (which is default) it will have additional field with stats since last refresh and totals since last refresh respectively
