### ISSUE TITLE
Build unsuccesful by go install

### ISSUE THREAD

**Issue by Caranthir** [arriven/db1000n#566]
I should be able to build from the repository by myself by 
`go install github.com/Arriven/db1000n@latest`
It doesn't work. It seems that it cannot find the URLs for the configuration files, when I build it myself.

This is the log file:
```
info	running db1000n	{"version": "v0.0.1", "pid": 16051}
info	checking IP address,	{"iter": 1}
info	location info	{"country": "*******", "ip": "*********"}
warn	failed to fetch config	{"path": "", "error": "open : no such file or directory"}
info	the config has not changed. Keep calm and carry on!
```

Please provide the necessary steps to build it myself or add the necessary files to the repository. 

I am trying to run it on Android with Termux. I need to build it myself. It doesn't work with the prebuilt files.

**Comment by arriven** [comment]
Yeah, if you build from the source you have to specify the path to the config manually via the `-c` flag. You can check the links in the prebuilt binary (`-help` should show default values) or in the terraform examples that also build the app from source (like https://github.com/arriven/db1000n/blob/main/terraform/heroku/variables.tf)

**Comment by Caranthir** [comment]
Thanks for the answer.
Now when I enter the link to the config file, I get the following error:
`warn	can't decrypt config	{"error": "encryption not supported"}`
What am I missing?

**Comment by Caranthir** [comment]
Latest release seems to have resolved the issue. But now I get the following error:
`error	error running job	{"name": "", "type": "encrypted", "error": "no identity matched any of the recipients"}`
Nevertheless it seems to be working.

**Comment by arriven** [comment]
yes, that last one is expected when you're building from source since you don't have a private encryption key for some jobs (you can check #394 as to why they're needed at all)
