### ISSUE TITLE
Only seems to attack 3 IPs

### ISSUE THREAD

**Issue by WeGoToMars** [Arriven/db1000n#58]
With -i 0 flag on launch, the only IPs visible in the log are
`[DEBUG] 194.54.14.187:53 started at XYZ`
`[DEBUG] 194.54.14.186:53 started at XYZ`
`[DEBUG] 194.67.2.109:53 started at XYZ`
No other targets are visible

Sometimes there are fail messages like 
`[DEBUG] GET https://bezformata.com/ failed at 1646319728 with code 403`

With only 3 targets working out of 59, it doesn't seem to be effective

**Comment by bunge12** [comment]
My output looks different, but I can also see only one IP (`178.248.236.218`)

![image](https://user-images.githubusercontent.com/54365622/156629706-c2584b85-9ae7-4f05-8519-f0ad9218b646.png)

**Comment by Arriven** [comment]
@alextatarinov @arthur2406 @bunge12 you're using a mode that only shows important logs, the IP there is from one of the experimental jobs that doesn't respect that (and there's already a bit more effective job with the same functionality, we just didn't get to reconfiguring that target yet). If you want to see all the info - add `-l 0` to the commandline arguments to enable debug logging (but be careful, there's a lot of it)
@WeGoToMars since you were using debug logs already, can you check it out with the latest version and provide a full log of an app running for at least a minute?

**Comment by WeGoToMars** [comment]
@Arriven downloaded latest build for amd64, running on win11
here is a piece of the log I'm seeing https://pastebin.com/raKTKG8n, it's not a full minute because pastebin has limit for free users, but it really stays the same.

On a side note, there seems to be some kind of an error with calculating the speed, it seems to drift upwards but network activity in task manager never changes (~2.5 mbps up/~4.5 mbps down).

![image](https://user-images.githubusercontent.com/47947772/156632694-bd5f84ac-a5b9-4432-8a90-a46c4db543c7.png)

**Comment by Andrii-L-DDoSer** [comment]
My results:


`docker run --rm -it ghcr.io/arriven/db1000n:latest`



<img width="1479" alt="Screenshot 2022-03-03 at 20 43 07" src="https://user-images.githubusercontent.com/100500001/156640786-a32180be-bcbe-44fe-9cfc-74aa88c78496.png">

**Comment by Arriven** [comment]
@WeGoToMars the log you provided this time also doesn't seem to include debug logs :)
The main reason network usage drifts up and down here is that the job outputting it's IP doesn't contribute to the overall metrics (it's simply an integrated module and will be replaced by other, more effective job). You can try out the backup config embedded into the app (it uses latest features) in the latest release by providing an invalid url for the main config (for example run it with `-c https://blah`). Coordinators will soon update the default remote config to use latest features but it's already effective as is

**Comment by WeGoToMars** [comment]
@Arriven `-c httpsL//blah` completely fixed the issue for me, it now works on multiple IPs and shows logs correctly. Thanks!

**Comment by Arriven** [comment]
@WeGoToMars cool, but please check https://github.com/db1000n-coordinators/LoadTestConfig and remove that commandline argument as soon as activity starts there to keep being up to date with current targets (I've almost finished instructing admins on how to manage it so it should become active very soon)

**Comment by WeGoToMars** [comment]
@Arriven `db1000n.exe -c https://github.com/db1000n-coordinators/LoadTestConfig/blob/main/config.json` seems to work now

Without any arguments, the logging works differently(?)

db1000n.exe -c https://github.com/db1000n-coordinators/LoadTestConfig/blob/main/config.json:
`[INFO] Attacking https://lenta.ru/`
`[INFO] Attacking https://lenta.ru/login`
`...`

db1000n.exe:
`[INFO] Атака проводиться успішно! Руський воєнний корабль іди нахуй!`
`[INFO] The app is generating approximately 34394 bytes per second`
_It prints this stat every minute, and it would be great if it could be more frequent (once every 1-10s)_

db1000n.exe -l 0 shows attacks on all 6 targets outlined in the [LoadTestConfig/main/config.json](https://raw.githubusercontent.com/db1000n-coordinators/LoadTestConfig/main/config.json)
