### ISSUE TITLE
Docker stopped after several seconds 

### ISSUE THREAD

**Issue by b0nn1e** [Arriven/db1000n#63]
Hi!

After several second docker has been stopped. Log below

```
root@vds2140872:~# docker run ghcr.io/arriven/db1000n:latest
2022/03/03 16:56:31 178.248.236.218 is already an IP address, skipping DNS resolution
2022/03/03 16:56:31 178.248.236.218 is already an IP address, skipping DNS resolution
⠧ Flood is in progress, target=178.248.236.218:80, floodType=random, payloadLength=1000 (5.3 MB, 383.465 kB/s)
root@vds2140872:~# 
```

Can you help with the fix?

**Comment by Arriven** [comment]
How much RAM is allocated to docker? See #54 as it seems to have pretty similar symptoms.
If it turns out to be something else and increasing the allocated RAM doesn't fix the issue feel free to reopen the issue and I'll try to look more into it.
