### ISSUE TITLE
Docker image won't run on arm64 devices

### ISSUE THREAD

**Issue by Wirtos** [Arriven/db1000n#67]
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`
Probably should be universal single-image-fits-all for easier scaling?

**Comment by Arriven** [comment]
Yup, need to take a look into it

**Comment by Arriven** [comment]
I anyone already knows how to do it - feel free to contribute

**Comment by Bleach665** [comment]
Also pls fix this for ````install.sh````.

**Comment by securims** [comment]
this is just a warning and it should be working still, if it bothers you run the command with the additional flag `docker run --platform linux/amd64 --pull always ghcr.io/arriven/db1000n:latest`

**Comment by Arriven** [comment]
The issue was fixed in #80 and also there was a fix for install.sh in #81 
Thanks authors of those requests for help!

**Comment by Bleach665** [comment]
Unfortunately not.  
````sudo ./install.sh```` 
failder with error 
````unknown: aarch64````.

**Comment by Arriven** [comment]
@Bleach665 hmm, seems like it can't detect your platform properly, which system are you running it on? Also can you try without sudo?

**Comment by Bleach665** [comment]
@Arriven . Oracle cloud arm instance.
````Linux arm 5.11.0-1028-oracle #31~20.04.1-Ubuntu SMP Wed Jan 26 14:20:52 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux````

**Comment by Arriven** [comment]
Ah, okay, I see, can you open a new issue and provide the value of your OSARCH and OSTYPE variables?
