### ISSUE TITLE
Implement or integrate more sophisticated attack patterns

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#7]
syn-flood already integrated from https://github.com/bilalcaliskan/syn-flood

Use this commit as an example for integrations https://github.com/Arriven/db1000n/commit/9470ea16033a140cd130b722a7693d896988b9ac

List of potential options:

- [x] #8
- [x] #15
- [x] #16

**Comment by Arriven** [comment]
Feel free to add more options with technical info, I'll be creating sub-tasks

**Comment by o-volkov** [comment]
slowloris - https://github.com/valyala/goloris
