### ISSUE TITLE
Маловато запросов в секунду можно в ~10 раз лучше

### ISSUE THREAD

**Issue by vinnik-dmitry07** [Arriven/db1000n#73]
![image](https://user-images.githubusercontent.com/24797359/156672647-2fac3e52-f41d-4a93-be05-6a253937c1f3.png)
![image](https://user-images.githubusercontent.com/24797359/156672682-82b957b9-7ab8-41e9-91f5-312533fa1337.png)
Посмотрите сорсы LOIC:
https://github.com/NewEraCracker/LOIC

**Comment by Arriven** [comment]
There are more effecient jobs in this program that do that task more effeciently (See #57 for some explanations on the topic). Also it seems like @securims just authored a PR (#76) that allows to use similar configuration with http traffic for those who think this is still a concern
