### ISSUE TITLE
 ERRO[0174] error waiting for container: EOF 

### ISSUE THREAD

**Issue by mvkorobkov** [Arriven/db1000n#75]
останавливается по ошибке
добавьте докеркомпоз с авторестартом и заодно многопоточностью

**Comment by mvkorobkov** [comment]
docker-compose.yml:

version: '3'
services:
  d1:
    image: ghcr.io/arriven/db1000n:latest
    restart: always

-----
docker-compose up --scale d1=5

**Comment by mvkorobkov** [comment]
похоже падает сам докер, нужно другое решение

**Comment by Arriven** [comment]
Feel free to make a pull request with that docker compose or use an executable directly on your system. You can check #54 for the most common issue with docker/cloud and check for workarounds there.
Also I'm not sure scaling docker compose on 1 machine is effective - from what I know most of techniques for ddos are limited either by the amount of unique IPs attacking the system (you'd need to setup docker differently to have that benefit with multiple instances) or by the amount of sheer resources allocated to it (which are limited by the amount of host system resources anyway)
