### ISSUE TITLE
DNS stress

### ISSUE THREAD

**Issue by Arriven** [Arriven/db1000n#8]
- could integrate https://github.com/MickaelBergem/dnsstresss/blob/master/dnsstresss.go

**Comment by lonli078** [comment]
I will do it

**Comment by arfgdev** [comment]
@lonli078 how is it going? do you need any help?

**Comment by AndriiChuzhynov** [comment]
working on it

**Comment by AndriiChuzhynov** [comment]
I think this can be closed
