### ISSUE TITLE
The app doesn't seem to generate any traffic, please contact your admin

### ISSUE THREAD

**Issue by QDanteQ** [Arriven/db1000n#82]
WARN]  2022/03/04 12:49:51 [WARN] The app doesn't seem to generate any traffic, please contact your admin
[ERROR] 2022/03/04 12:49:51 github.com/Arriven/db1000n/logs.Logger.Error:logs.go:50 [ERROR] error sending packet: listen ip4:tcp 0.0.0.0: socket: operation not permitted
[ERROR] 2022/03/04 12:49:51 github.com/Arriven/db1000n/logs.Logger.Error:logs.go:50 [ERROR] error sending packet: listen ip4:tcp 0.0.0.0: socket: operation not permitted
[ERROR] 2022/03/04 12:49:51 github.com/Arriven/db1000n/logs.Logger.Error:logs.go:50 [ERROR] error sending packet: listen ip4:tcp 0.0.0.0: socket: operation not permitted
[ERROR] 2022/03/04 12:49:51 github.com/Arriven/db1000n/logs.Logger.Error:logs.go:50 [ERROR] error sending packet: listen ip4:tcp 0.0.0.0: socket: operation not permitted
[ERROR] 2022/03/04 12:49:51 github.com/Arriven/db1000n/logs.Logger.Error:logs.go:50 [ERROR] error sending packet: listen ip4:tcp 0.0.0.0: socket: operation not permitted

**Comment by Arriven** [comment]
There was a small misconfiguration by the new admin, it was fixed within 10 minutes (see https://github.com/db1000n-coordinators/LoadTestConfig/commit/831f3fcaeed704aa294a5d12e1295e09389eb5c1)
