### ISSUE TITLE
dynamic targets list

### ISSUE THREAD

**Issue by Yneth** [Arriven/db1000n#85]
I have created an API for targets, currently it has info on cloudflare, UP/DOWN, ips and other stuff.
I am planning to add open ports info and add sorting based on popularity.

If you'd like I can share an access with you.

You can check it out here:
http://164.92.247.88:9300/

**Comment by Arriven** [comment]
Can you get in touch with @Andrmist ? He volunteered to write an automated config generator which would be used by admins and I think it would be best to integrate an option to fetch list of targets from a URL there

**Comment by Arriven** [comment]
See #78 for reference
