### ISSUE TITLE
Is there a benefit to running the program around the clock? 

### ISSUE THREAD

**Issue by TarasKasprik** [Arriven/db1000n#96]
Is there a benefit to running the program around the clock? 
Do you need to run it only after receiving a command from the coordinators? 

Different sources have different information on this issue.

**Comment by Arriven** [comment]
You can safely run this app around the clock. You can assume it restarts itself every minute and gets new targets

Restarts is an approximation, in reality it's a bit smarter than that but I won't go into details for now
